--
-- Structure de la table `blog`
--

-- DROP TABLE IF EXISTS `blog`;
-- CREATE TABLE IF NOT EXISTS `blog` (
--   `id` varbinary(16) NOT NULL,
--   `owner_id` varbinary(16) NOT NULL,
--   `author_id` varbinary(16) NOT NULL,
--   `content` mediumtext CHARACTER SET utf8mb4 NOT NULL,
--   `draft` mediumtext CHARACTER SET utf8mb4 NOT NULL,
--   `create_time` int(11) unsigned NOT NULL DEFAULT '0',
--   `publish_time` int(11) unsigned NOT NULL DEFAULT '0',
--   `edit_time` int(11) unsigned NOT NULL DEFAULT '0',
--   `rating` double NOT NULL DEFAULT '0',
--   `lang` varchar(10) NOT NULL DEFAULT '',
--   `status` enum('online', 'offline', 'draft', 'trash', 'archive') NOT NULL DEFAULT 'draft',
--   `version` int(10) unsigned NOT NULL DEFAULT '0',
--   `counter` int(10) unsigned NOT NULL DEFAULT '0',
--   PRIMARY KEY (`id`),
--   KEY `owner_id` (`owner_id`),
--   KEY `author_id` (`author_id`),
--   KEY `create_time` (`create_time`),
--   KEY `publish_time` (`publish_time`),
--   KEY `status` (`status`),
--   FULLTEXT KEY `content` (`content`)
-- ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

