ALTER TABLE attachments  CHANGE `filename` `filename` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci; 
ALTER TABLE attachments  CHANGE `filetype` `filetype` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci; 
ALTER TABLE contacts  CHANGE `firstname` `firstname` varchar(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci;      
ALTER TABLE contacts  CHANGE `lastname` `lastname` varchar(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci;          
ALTER TABLE contacts  CHANGE `nickname` `nickname` varchar(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci;         
ALTER TABLE contacts  CHANGE `org` `org` varchar(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci;              
ALTER TABLE contacts  CHANGE `categories` `categories`  varchar(50) CHARACTER SET ascii COLLATE ascii_general_ci;  
ALTER TABLE contacts  CHANGE `title` `title`  varchar(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci;             
ALTER TABLE contacts  CHANGE `photo` `photo`  varchar(150) CHARACTER SET ascii COLLATE ascii_general_ci; 
ALTER TABLE contacts  CHANGE `tel_work` `tel_work`  varchar(30) CHARACTER SET ascii COLLATE ascii_general_ci;      
ALTER TABLE contacts  CHANGE `tel_home` `tel_home`  varchar(30) CHARACTER SET ascii COLLATE ascii_general_ci;      
ALTER TABLE contacts  CHANGE `tel_cell` `tel_cell`  varchar(30) CHARACTER SET ascii COLLATE ascii_general_ci;      
ALTER TABLE contacts  CHANGE `adr_work` `adr_work`  varchar(160) CHARACTER SET utf8 COLLATE utf8_unicode_ci;        
ALTER TABLE contacts  CHANGE `label_work` `label_work` varchar(160) CHARACTER SET utf8 COLLATE utf8_unicode_ci;     
ALTER TABLE contacts  CHANGE `adr_home` `adr_home` varchar(160) CHARACTER SET utf8 COLLATE utf8_unicode_ci;       
ALTER TABLE contacts  CHANGE `label_home` `label_home` varchar(160) CHARACTER SET utf8 COLLATE utf8_unicode_ci;     
ALTER TABLE contacts  CHANGE `email` `email` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;          
ALTER TABLE contacts  CHANGE `web_site` `web_site` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;         
ALTER TABLE contacts  CHANGE `fingerprint` `fingerprin`  varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;     
ALTER TABLE contacts  CHANGE `email_work` `email_work` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;        
ALTER TABLE contacts  CHANGE `email_home` `email_home` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;       
ALTER TABLE contacts  CHANGE `x-primary-phone` `x-primary-phone` varchar(30) CHARACTER SET ascii COLLATE ascii_general_ci; 
ALTER TABLE contacts  CHANGE `note` `note`   varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;           
ALTER TABLE contacts  CHANGE `tag` `tag` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci;             
ALTER TABLE contacts  CHANGE `vcard` `vcard` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci; 

ALTER TABLE layout DROP INDEX content;   
ALTER TABLE layout DROP INDEX footnote;   
ALTER TABLE layout CHANGE `author` `author` varchar(80) CHARACTER SET ascii COLLATE ascii_general_ci;          
ALTER TABLE layout CHANGE `comment` `comment` varchar(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci;        
ALTER TABLE layout CHANGE `content` `content` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci;       
ALTER TABLE layout CHANGE `backup` `backup` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci;              
ALTER TABLE layout CHANGE `status` `status` enum('active','deleted','locked','backup','readonly','draft')  CHARACTER SET ascii COLLATE ascii_general_ci;
ALTER TABLE layout ADD FULLTEXT `content` (`content`, `comment`, `backup`);

ALTER TABLE media DROP INDEX content;   
ALTER TABLE media  CHANGE `file_path` `file_path` varchar(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci;       
ALTER TABLE media  CHANGE `user_filename` `user_filename` varchar(80) CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE media  CHANGE `metadata` `metadata` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci;         
ALTER TABLE media  CHANGE `caption` `caption` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci;          
ALTER TABLE media ADD FULLTEXT `content` (`caption`, `user_filename`, `file_path`, `metadata`);