ALTER TABLE areas CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE communities CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sites CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE contacts CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE hashtag CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE mark CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE notice CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE preferences CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE profile CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;


-- ALTER DATABASE B_somanos CHARACTER SET utf8 COLLATE utf8_general_ci;