ALTER TABLE acl CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE attachments CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE dmails CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layout CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE params CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;


-- ALTER DATABASE B_somanos CHARACTER SET utf8 COLLATE utf8_general_ci;