
-- ALTER TABLE comment DROP PRIMARY KEY;
-- ALTER TABLE comment ADD UNIQUE(`id`);
-- ALTER TABLE comment ADD `sys_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
-- ALTER TABLE comment ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

ALTER TABLE  `comment` MODIFY  `ref_id` VARCHAR(16);
ALTER TABLE  `comment` MODIFY  `id` VARCHAR(16);
ALTER TABLE  `comment` MODIFY  `owner_id` VARCHAR(16);
ALTER TABLE  `comment` MODIFY  `author_id` VARCHAR(16);

