-- =================================
-- Structure de la table `dmails`
-- =================================
DROP TABLE IF EXISTS `dmails`;
CREATE TABLE IF NOT EXISTS `dmails` (
  `id` varbinary(16) NOT NULL,
  `dest_id` varbinary(16) NOT NULL,
  `dest_firstname` text CHARACTER SET utf8mb4 NOT NULL,
  `dest_lastname` text CHARACTER SET utf8mb4 NOT NULL,
  `dest_email` varchar(255) CHARACTER SET ascii NOT NULL,
  `sender_id` varbinary(16) NOT NULL,
  `sender_firstname` text CHARACTER SET utf8mb4 NOT NULL,
  `sender_lastname` text CHARACTER SET utf8mb4 NOT NULL,
  `sender_email` varchar(255) CHARACTER SET ascii NOT NULL,
  `thread_id` varbinary(40) NOT NULL,
  `source` enum('dmail','email') NOT NULL,
  `subject` text CHARACTER SET utf8mb4 NOT NULL,
  `summary` text CHARACTER SET utf8mb4 NOT NULL,
  `content` mediumtext CHARACTER SET utf8mb4 NOT NULL,
  `data` longtext NOT NULL,
  `to` varchar(255) CHARACTER SET ascii NOT NULL,
  `cc` varchar(255) CHARACTER SET ascii NOT NULL,
  `bcc` varchar(255) CHARACTER SET ascii NOT NULL,
  `email_header` longtext NOT NULL,
  `folder` text CHARACTER SET utf8mb4 NOT NULL,
  `folder_id` varbinary(40) NOT NULL,
  `folder_tag` varchar(300) CHARACTER SET utf8mb4 NOT NULL,
  `imap_folder` text CHARACTER SET utf8mb4 NOT NULL,
  `publish_time` int(11) unsigned NOT NULL DEFAULT '0',
  `thread_rank` tinyint(4) NOT NULL DEFAULT '0',
  `msg_status` enum('new','seen','archived','deleted','draft','sent','important') NOT NULL DEFAULT 'new',
  `status` enum('draft','sent','deleted') NOT NULL DEFAULT 'draft',
  `read` enum('New','Seen','Archived','Deleted','Important') NOT NULL,
  `seen` tinyint(2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sender_id` (`sender_id`),
  KEY `dest_id` (`dest_id`),
  KEY `folder_id` (`folder_id`),
  KEY `thread_id` (`thread_id`),
  KEY `publish_time` (`publish_time`),
  KEY `read` (`read`),
  KEY `msg_status` (`msg_status`),
  KEY `folder_tag` (`folder_tag`(250)),
  KEY `enveloppe` (`dest_email`),
  FULLTEXT KEY `folder` (`folder`),
  FULLTEXT KEY `subject` (`subject`),
  FULLTEXT KEY `contacts` (`dest_lastname`,`dest_firstname`,`sender_lastname`,`sender_firstname`),
  FULLTEXT KEY `message` (`subject`,`content`),
  FULLTEXT KEY `every_text` (`subject`,`content`,`folder`,`dest_firstname`,`dest_lastname`,`sender_firstname`,`sender_lastname`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
