ALTER TABLE `hubs` DROP PRIMARY KEY;
ALTER TABLE `hubs` ADD UNIQUE(`id`);
ALTER TABLE `hubs` ADD `sys_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE hubs ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;