-- ALTER TABLE `entity` CHANGE `ident` `ident` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '';
ALTER TABLE acl engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;              
ALTER TABLE areas engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;            
ALTER TABLE attachments engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;      
ALTER TABLE communities engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;      
ALTER TABLE contacts engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;         
ALTER TABLE dmails engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;           
ALTER TABLE hashtag engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;          
ALTER TABLE layout engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;           
ALTER TABLE mark engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;             
ALTER TABLE media engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;            
ALTER TABLE notice engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;           
ALTER TABLE params engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;           
ALTER TABLE preferences engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;      
ALTER TABLE profile engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;          
ALTER TABLE tag engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;              
ALTER TABLE vcore engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;            
ALTER TABLE vjournal engine=innoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;         
