insert into `language` values("af", "af-NA",  "Afrikaans (Namibia)", "", "");
insert into `language` values("af", "af-ZA",  "Afrikaans (South Africa)", "", "");
insert into `language` values("af", "af",  "Afrikaans", "", "");
insert into `language` values("ak", "ak-GH",  "Akan (Ghana)", "", "");
insert into `language` values("ak", "ak",  "Akan", "", "");
insert into `language` values("sq", "sq-AL",  "Albanian (Albania)", "", "");
insert into `language` values("sq", "sq",  "Albanian", "", "");
insert into `language` values("am", "am-ET",  "Amharic (Ethiopia)", "", "");
insert into `language` values("am", "am",  "Amharic", "", "");
insert into `language` values("ar", "ar-DZ",  "Arabic (Algeria)", "العربية", "");
insert into `language` values("ar", "ar-BH",  "Arabic (Bahrain)", "العربية", "");
insert into `language` values("ar", "ar-EG",  "Arabic (Egypt)", "العربية", "");
insert into `language` values("ar", "ar-IQ",  "Arabic (Iraq)", "العربية", "");
insert into `language` values("ar", "ar-JO",  "Arabic (Jordan)", "العربية", "");
insert into `language` values("ar", "ar-KW",  "Arabic (Kuwait)", "العربية", "");
insert into `language` values("ar", "ar-LB",  "Arabic (Lebanon)", "العربية", "");
insert into `language` values("ar", "ar-LY",  "Arabic (Libya)", "العربية", "");
insert into `language` values("ar", "ar-MA",  "Arabic (Morocco)", "العربية", "");
insert into `language` values("ar", "ar-OM",  "Arabic (Oman)", "العربية", "");
insert into `language` values("ar", "ar-QA",  "Arabic (Qatar)", "العربية", "");
insert into `language` values("ar", "ar-SA",  "Arabic (Saudi Arabia)", "العربية", "");
insert into `language` values("ar", "ar-SD",  "Arabic (Sudan)", "العربية", "");
insert into `language` values("ar", "ar-SY",  "Arabic (Syria)", "العربية", "");
insert into `language` values("ar", "ar-TN",  "Arabic (Tunisia)", "العربية", "");
insert into `language` values("ar", "ar-AE",  "Arabic (United Arab Emirates)", "العربية", "");
insert into `language` values("ar", "ar-YE",  "Arabic (Yemen)", "العربية", "");
insert into `language` values("ar", "ar",  "Arabic", "العربية", "");
insert into `language` values("hy", "hy-AM",  "Armenian (Armenia)", "", "");
insert into `language` values("hy", "hy",  "Armenian", "", "");
insert into `language` values("as", "as-IN",  "Assamese (India)", "", "");
insert into `language` values("as", "as",  "Assamese", "", "");
insert into `language` values("asa", "asa-TZ",  "Asu (Tanzania)", "", "");
insert into `language` values("asa", "asa",  "Asu", "", "");
insert into `language` values("az", "az-Cyrl",  "Azerbaijani (Cyrillic)", "", "");
insert into `language` values("az", "az-Cyrl-AZ",  "Azerbaijani (Cyrillic, Azerbaijan)", "", "");
insert into `language` values("az", "az-Latn",  "Azerbaijani (Latin)", "", "");
insert into `language` values("az", "az-Latn-AZ",  "Azerbaijani (Latin, Azerbaijan)", "", "");
insert into `language` values("az", "az",  "Azerbaijani", "", "");
insert into `language` values("bm", "bm-ML",  "Bambara (Mali)", "", "");
insert into `language` values("bm", "bm",  "Bambara", "", "");
insert into `language` values("eu", "eu-ES",  "Basque (Spain)", "", "");
insert into `language` values("eu", "eu",  "Basque", "", "");
insert into `language` values("be", "be-BY",  "Belarusian (Belarus)", "", "");
insert into `language` values("be", "be",  "Belarusian", "", "");
insert into `language` values("bem", "bem-ZM",  "Bemba (Zambia)", "", "");
insert into `language` values("bem", "bem",  "Bemba", "", "");
insert into `language` values("bez", "bez-TZ",  "Bena (Tanzania)", "", "");
insert into `language` values("bez", "bez",  "Bena", "", "");
insert into `language` values("bn", "bn-BD",  "Bengali (Bangladesh)", "", "");
insert into `language` values("bn", "bn-IN",  "Bengali (India)", "", "");
insert into `language` values("bn", "bn",  "Bengali", "", "");
insert into `language` values("bs", "bs-BA",  "Bosnian (Bosnia and Herzegovina)", "", "");
insert into `language` values("bs", "bs",  "Bosnian", "", "");
insert into `language` values("bg", "bg-BG",  "Bulgarian (Bulgaria)", "Български", "");
insert into `language` values("bg", "bg",  "Bulgarian", "Български", "");
insert into `language` values("my", "my-MM",  "Burmese (Myanmar [Burma])", "", "");
insert into `language` values("my", "my",  "Burmese", "", "");
insert into `language` values("ca", "ca-ES",  "Catalan (Spain)", "", "");
insert into `language` values("ca", "ca",  "Catalan", "", "");
insert into `language` values("tzm", "tzm-Latn",  "Central Morocco Tamazight (Latin)", "", "");
insert into `language` values("tzm", "tzm-Latn-MA",  "Central Morocco Tamazight (Latin, Morocco)", "", "");
insert into `language` values("tzm", "tzm",  "Central Morocco Tamazight", "", "");
insert into `language` values("chr", "chr-US",  "Cherokee (United States)", "", "");
insert into `language` values("chr", "chr",  "Cherokee", "", "");
insert into `language` values("cgg", "cgg-UG",  "Chiga (Uganda)", "", "");
insert into `language` values("cgg", "cgg",  "Chiga", "", "");
insert into `language` values("zh", "zh-Hans",  "Chinese (Simplified Han)", "汉语", "");
insert into `language` values("zh", "zh-Hans-CN",  "Chinese (Simplified Han, China)", "汉语", "");
insert into `language` values("zh", "zh-Hans-HK",  "Chinese (Simplified Han, Hong Kong SAR China)", "华语", "");
insert into `language` values("zh", "zh-Hans-MO",  "Chinese (Simplified Han, Macau SAR China)", "华语", "");
insert into `language` values("zh", "zh-Hans-SG",  "Chinese (Simplified Han, Singapore)", "华语", "");
insert into `language` values("zh", "zh-Hant",  "Chinese (Traditional Han)", "漢語", "");
insert into `language` values("zh", "zh-Hant-HK",  "Chinese (Traditional Han, Hong Kong SAR China)", "華語", "");
insert into `language` values("zh", "zh-Hant-MO",  "Chinese (Traditional Han, Macau SAR China)", "華語", "");
insert into `language` values("zh", "zh-Hant-TW",  "Chinese (Traditional Han, Taiwan)", "華語", "");
insert into `language` values("zh", "zh",  "Chinese", "中文", "");
insert into `language` values("kw", "kw-GB",  "Cornish (United Kingdom)", "", "");
insert into `language` values("kw", "kw",  "Cornish", "", "");
insert into `language` values("hr", "hr-HR",  "Croatian (Croatia)", "", "");
insert into `language` values("hr", "hr",  "Croatian", "", "");
insert into `language` values("cs", "cs-CZ",  "Czech (Czech Republic)", "Čeština", "");
insert into `language` values("cs", "cs",  "Czech", "Čeština", "");
insert into `language` values("da", "da-DK",  "Danish (Denmark)", "", "");
insert into `language` values("da", "da",  "Danish", "", "");
insert into `language` values("nl", "nl-BE",  "Dutch (Belgium)", "", "");
insert into `language` values("nl", "nl-NL",  "Dutch (Netherlands)", "", "");
insert into `language` values("nl", "nl",  "Dutch", "", "");
insert into `language` values("ebu", "ebu-KE",  "Embu (Kenya)", "", "");
insert into `language` values("ebu", "ebu",  "Embu", "", "");
insert into `language` values("en", "en-AS",  "English (American Samoa)", "", "");
insert into `language` values("en", "en-AU",  "English (Australia)", "", "");
insert into `language` values("en", "en-BE",  "English (Belgium)", "", "");
insert into `language` values("en", "en-BZ",  "English (Belize)", "", "");
insert into `language` values("en", "en-BW",  "English (Botswana)", "", "");
insert into `language` values("en", "en-CA",  "English (Canada)", "", "");
insert into `language` values("en", "en-GU",  "English (Guam)", "", "");
insert into `language` values("en", "en-HK",  "English (Hong Kong SAR China)", "", "");
insert into `language` values("en", "en-IN",  "English (India)", "", "");
insert into `language` values("en", "en-IE",  "English (Ireland)", "", "");
insert into `language` values("en", "en-JM",  "English (Jamaica)", "", "");
insert into `language` values("en", "en-MT",  "English (Malta)", "", "");
insert into `language` values("en", "en-MH",  "English (Marshall Islands)", "", "");
insert into `language` values("en", "en-MU",  "English (Mauritius)", "", "");
insert into `language` values("en", "en-NA",  "English (Namibia)", "", "");
insert into `language` values("en", "en-NZ",  "English (New Zealand)", "", "");
insert into `language` values("en", "en-MP",  "English (Northern Mariana Islands)", "", "");
insert into `language` values("en", "en-PK",  "English (Pakistan)", "", "");
insert into `language` values("en", "en-PH",  "English (Philippines)", "", "");
insert into `language` values("en", "en-SG",  "English (Singapore)", "", "");
insert into `language` values("en", "en-ZA",  "English (South Africa)", "", "");
insert into `language` values("en", "en-TT",  "English (Trinidad and Tobago)", "", "");
insert into `language` values("en", "en-UM",  "English (U.S. Minor Outlying Islands)", "", "");
insert into `language` values("en", "en-VI",  "English (U.S. Virgin Islands)", "", "");
insert into `language` values("en", "en-GB",  "English (United Kingdom)", "", "");
insert into `language` values("en", "en-US",  "English (United States)", "", "");
insert into `language` values("en", "en-ZW",  "English (Zimbabwe)", "", "");
insert into `language` values("en", "en", "English", "", "");
insert into `language` values("eo", "eo","Esperanto", "", "");
insert into `language` values("et", "et-EE",  "Estonian (Estonia)", "", "");
insert into `language` values("et", "et",  "Estonian", "", "");
insert into `language` values("ee", "ee-GH",  "Ewe (Ghana)", "", "");
insert into `language` values("ee", "ee-TG",  "Ewe (Togo)", "", "");
insert into `language` values("ee", "ee",  "Ewe", "", "");
insert into `language` values("fo", "fo-FO",  "Faroese (Faroe Islands)", "", "");
insert into `language` values("fo", "fo",  "Faroese", "", "");
insert into `language` values("fil", "fil-PH",  "Filipino (Philippines)", "", "");
insert into `language` values("fil", "fil",  "Filipino", "", "");
insert into `language` values("fi", "fi-FI",  "Finnish (Finland)", "", "");
insert into `language` values("fi", "fi",  "Finnish", "", "");
insert into `language` values("fr", "fr-BE",  "French (Belgium)", "Français (Belgique)", "");
insert into `language` values("fr", "fr-BJ",  "French (Benin)", "Français (Benin)", "");
insert into `language` values("fr", "fr-BF",  "French (Burkina Faso)", "Français (Burkina Faso)", "");
insert into `language` values("fr", "fr-BI",  "French (Burundi)", "Français (Burundi)", "");
insert into `language` values("fr", "fr-CM",  "French (Cameroon)", "Français (Cameroune)", "");
insert into `language` values("fr", "fr-CA",  "French (Canada)", "Français (Canada)", "");
insert into `language` values("fr", "fr-CF",  "French (Central African Republic)", "Français (République Centre Africaine)", "");
insert into `language` values("fr", "fr-TD",  "French (Chad)", "Français (Chad)", "");
insert into `language` values("fr", "fr-KM",  "French (Comoros)", "Français (Comores)", "");
insert into `language` values("fr", "fr-CG",  "French (Congo - Brazzaville)", "Français (Congo - Brazzaville)", "");
insert into `language` values("fr", "fr-CD",  "French (Congo - Kinshasa)", "Français (Congo - Kinshasa)", "");
insert into `language` values("fr", "fr-CI",  "French (Yvory Coast)", "Français (Côte d’Ivoire)", "");
insert into `language` values("fr", "fr-DJ",  "French (Djibouti)", "Français (Djibouti)", "");
insert into `language` values("fr", "fr-GQ",  "French (Equatorial Guinea)", "Français (Guinée Equatoriale)", "");
insert into `language` values("fr", "fr-FR",  "French (France)", "Français (France)", "");
insert into `language` values("fr", "fr-GA",  "French (Gabon)", "Français (Gabon)", "");
insert into `language` values("fr", "fr-GP",  "French (Guadeloupe)", "Français (Guadeloupe)", "");
insert into `language` values("fr", "fr-GN",  "French (Guinea)", "", "Français (Guinée)");
insert into `language` values("fr", "fr-LU",  "French (Luxembourg)", "Français (Luxembourg)", "");
insert into `language` values("fr", "fr-MG",  "French (Madagascar)", "Français (Madagascar)", "");
insert into `language` values("fr", "fr-ML",  "French (Mali)", "Français (Mali)", "");
insert into `language` values("fr", "fr-MQ",  "French (Martinique)", "Français (Martinique)", "");
insert into `language` values("fr", "fr-MC",  "French (Monaco)", "Français (Monaco)", "");
insert into `language` values("fr", "fr-NE",  "French (Niger)", "Français (Niger)", "");
insert into `language` values("fr", "fr-RW",  "French (Rwanda)", "Français (Rwanda)", "");
insert into `language` values("fr", "fr-RE",  "French (Réunion)", "Français (Réunion)", "");
insert into `language` values("fr", "fr-BL",  "French (Saint Barthelemy)", "Français (Saint Barthélemy)", "");
insert into `language` values("fr", "fr-MF",  "French (Saint Martin)", "Français (Saint Martin)", "");
insert into `language` values("fr", "fr-SN",  "French (Senegal)", "Français (Sénégal)", "");
insert into `language` values("fr", "fr-CH",  "French (Switzerland)", "Français (Suisse)", "");
insert into `language` values("fr", "fr-TG",  "French (Togo)", "Français (Togo)", "");
insert into `language` values("fr", "fr",  "French", "Français", "Générique");
insert into `language` values("ff", "ff-SN",  "Fulah (Senegal)", "", "");
insert into `language` values("ff", "ff",  "Fulah", "", "");
insert into `language` values("gl", "gl-ES",  "Galician (Spain)", "", "");
insert into `language` values("gl", "gl",  "Galician", "", "");
insert into `language` values("lg", "lg-UG",  "Ganda (Uganda)", "", "");
insert into `language` values("lg", "lg",  "Ganda", "", "");
insert into `language` values("ka", "ka-GE",  "Georgian (Georgia)", "", "");
insert into `language` values("ka", "ka",  "Georgian", "", "");
insert into `language` values("de", "de-AT",  "German (Austria)", "", "");
insert into `language` values("de", "de-BE",  "German (Belgium)", "", "");
insert into `language` values("de", "de-DE",  "German (Germany)", "", "");
insert into `language` values("de", "de-LI",  "German (Liechtenstein)", "", "");
insert into `language` values("de", "de-LU",  "German (Luxembourg)", "", "");
insert into `language` values("de", "de-CH",  "German (Switzerland)", "", "");
insert into `language` values("de", "de",  "German", "", "");
insert into `language` values("el", "el-CY",  "Greek (Cyprus)", "", "");
insert into `language` values("el", "el-GR",  "Greek (Greece)", "", "");
insert into `language` values("el", "el",  "Greek", "", "");
insert into `language` values("gu", "gu-IN",  "Gujarati (India)", "", "");
insert into `language` values("gu", "gu",  "Gujarati", "", "");
insert into `language` values("guz", "guz-KE",  "Gusii (Kenya)", "", "");
insert into `language` values("guz", "guz",  "Gusii", "", "");
insert into `language` values("ha", "ha-Latn",  "Hausa (Latin)", "", "");
insert into `language` values("ha", "ha-Latn-GH",  "Hausa (Latin, Ghana)", "", "");
insert into `language` values("ha", "ha-Latn-NE",  "Hausa (Latin, Niger)", "", "");
insert into `language` values("ha", "ha-Latn-NG",  "Hausa (Latin, Nigeria)", "", "");
insert into `language` values("ha", "ha",  "Hausa", "", "");
insert into `language` values("haw", "haw-US",  "Hawaiian (United States)", "", "");
insert into `language` values("haw", "haw",  "Hawaiian", "", "");
insert into `language` values("he", "he-IL",  "Hebrew (Israel)", "", "");
insert into `language` values("he", "he",  "Hebrew", "", "");
insert into `language` values("hi", "hi-IN",  "Hindi (India)", "", "");
insert into `language` values("hi", "hi",  "Hindi", "", "");
insert into `language` values("hu", "hu-HU",  "Hungarian (Hungary)", "", "");
insert into `language` values("hu", "hu",  "Hungarian", "", "");
insert into `language` values("is", "is-IS",  "Icelandic (Iceland)", "", "");
insert into `language` values("is", "is",  "Icelandic", "", "");
insert into `language` values("ig", "ig-NG",  "Igbo (Nigeria)", "", "");
insert into `language` values("ig", "ig",  "Igbo", "", "");
insert into `language` values("id", "id-ID",  "Indonesian (Indonesia)", "", "");
insert into `language` values("id", "id",  "Indonesian", "", "");
insert into `language` values("ga", "ga-IE",  "Irish (Ireland)", "", "");
insert into `language` values("ga", "ga",  "Irish", "", "");
insert into `language` values("it", "it-IT",  "Italian (Italy)", "", "");
insert into `language` values("it", "it-CH",  "Italian (Switzerland)", "", "");
insert into `language` values("it", "it",  "Italian", "", "");
insert into `language` values("ja", "ja-JP",  "Japanese (Japan)", "日本語 (Japan)", "");
insert into `language` values("ja", "ja",  "Japanese", "日本語 (Japan)", "");
insert into `language` values("kea", "kea-CV",  "Kabuverdianu (Cape Verde)", "", "");
insert into `language` values("kea", "kea",  "Kabuverdianu", "", "");
insert into `language` values("kab", "kab-DZ",  "Kabyle (Algeria)", "", "");
insert into `language` values("kab", "kab",  "Kabyle", "", "");
insert into `language` values("kl", "kl-GL",  "Kalaallisut (Greenland)", "", "");
insert into `language` values("kl", "kl",  "Kalaallisut", "", "");
insert into `language` values("kln", "kln-KE",  "Kalenjin (Kenya)", "", "");
insert into `language` values("kln", "kln",  "Kalenjin", "", "");
insert into `language` values("kam", "kam-KE",  "Kamba (Kenya)", "", "");
insert into `language` values("kam", "kam",  "Kamba", "", "");
insert into `language` values("kn", "kn-IN",  "Kannada (India)", "", "");
insert into `language` values("kn", "kn",  "Kannada", "", "");
insert into `language` values("kk", "kk-Cyrl",  "Kazakh (Cyrillic)", "", "");
insert into `language` values("kk", "kk-Cyrl-KZ",  "Kazakh (Cyrillic, Kazakhstan)", "", "");
insert into `language` values("kk", "kk",  "Kazakh", "", "");
insert into `language` values("km", "km-KH",  "Khmer (Cambodia)", "", "");
insert into `language` values("km", "km",  "Khmer", "", "");
insert into `language` values("ki", "ki-KE",  "Kikuyu (Kenya)", "", "");
insert into `language` values("ki", "ki",  "Kikuyu", "", "");
insert into `language` values("rw", "rw-RW",  "Kinyarwanda (Rwanda)", "", "");
insert into `language` values("rw", "rw",  "Kinyarwanda", "", "");
insert into `language` values("kok", "kok-IN",  "Konkani (India)", "", "");
insert into `language` values("kok", "kok",  "Konkani", "", "");
insert into `language` values("ko", "ko-KR",  "Korean (South Korea)", "한국어 (South Korea)", "");
insert into `language` values("ko", "ko",  "Korean", "한국어", "");
insert into `language` values("khq", "khq-ML",  "Koyra Chiini (Mali)", "", "");
insert into `language` values("khq", "khq",  "Koyra Chiini", "", "");
insert into `language` values("ses", "ses-ML",  "Koyraboro Senni (Mali)", "", "");
insert into `language` values("ses", "ses",  "Koyraboro Senni", "", "");
insert into `language` values("lag", "lag-TZ",  "`Language`i (Tanzania)", "", "");
insert into `language` values("lag", "lag",  "`Language`i", "", "");
insert into `language` values("lv", "lv-LV",  "Latvian (Latvia)", "", "");
insert into `language` values("lv", "lv",  "Latvian", "", "");
insert into `language` values("lt", "lt-LT",  "Lithuanian (Lithuania)", "", "");
insert into `language` values("lt", "lt",  "Lithuanian", "", "");
insert into `language` values("luo", "luo-KE",  "Luo (Kenya)", "", "");
insert into `language` values("luo", "luo",  "Luo", "", "");
insert into `language` values("luy", "luy-KE",  "Luyia (Kenya)", "", "");
insert into `language` values("luy", "luy",  "Luyia", "", "");
insert into `language` values("mk", "mk-MK",  "Macedonian (Macedonia)", "", "");
insert into `language` values("mk", "mk",  "Macedonian", "", "");
insert into `language` values("jmc", "jmc-TZ",  "Machame (Tanzania)", "", "");
insert into `language` values("jmc", "jmc",  "Machame", "", "");
insert into `language` values("kde", "kde-TZ",  "Makonde (Tanzania)", "", "");
insert into `language` values("kde", "kde",  "Makonde", "", "");
insert into `language` values("mg", "mg-MG",  "Malagasy (Madagascar)", "", "");
insert into `language` values("mg", "mg",  "Malagasy", "", "");
insert into `language` values("ms", "ms-BN",  "Malay (Brunei)", "", "");
insert into `language` values("ms", "ms-MY",  "Malay (Malaysia)", "", "");
insert into `language` values("ms", "ms",  "Malay", "", "");
insert into `language` values("ml", "ml-IN",  "Malayalam (India)", "", "");
insert into `language` values("ml", "ml",  "Malayalam", "", "");
insert into `language` values("mt", "mt-MT",  "Maltese (Malta)", "", "");
insert into `language` values("mt", "mt",  "Maltese", "", "");
insert into `language` values("gv", "gv-GB",  "Manx (United Kingdom)", "", "");
insert into `language` values("gv", "gv",  "Manx", "", "");
insert into `language` values("mr", "mr-IN",  "Marathi (India)", "", "");
insert into `language` values("mr", "mr",  "Marathi", "", "");
insert into `language` values("mas", "mas-KE",  "Masai (Kenya)", "", "");
insert into `language` values("mas", "mas-TZ",  "Masai (Tanzania)", "", "");
insert into `language` values("mas", "mas",  "Masai", "", "");
insert into `language` values("mer", "mer-KE",  "Meru (Kenya)", "", "");
insert into `language` values("mer", "mer",  "Meru", "", "");
insert into `language` values("mfe", "mfe-MU",  "Morisyen (Mauritius)", "", "");
insert into `language` values("mfe", "mfe",  "Morisyen", "", "");
insert into `language` values("naq", "naq-NA",  "Nama (Namibia)", "", "");
insert into `language` values("naq", "naq",  "Nama", "", "");
insert into `language` values("ne", "ne-IN",  "Nepali (India)", "", "");
insert into `language` values("ne", "ne-NP",  "Nepali (Nepal)", "", "");
insert into `language` values("ne", "ne",  "Nepali", "", "");
insert into `language` values("nd", "nd-ZW",  "North Ndebele (Zimbabwe)", "", "");
insert into `language` values("nd", "nd",  "North Ndebele", "", "");
insert into `language` values("nb", "nb-NO",  "Norwegian Bokmål (Norway)", "", "");
insert into `language` values("nb", "nb",  "Norwegian Bokmål", "", "");
insert into `language` values("nn", "nn-NO",  "Norwegian Nynorsk (Norway)", "", "");
insert into `language` values("nn", "nn",  "Norwegian Nynorsk", "", "");
insert into `language` values("nyn", "nyn-UG",  "Nyankole (Uganda)", "", "");
insert into `language` values("nyn", "nyn",  "Nyankole", "", "");
insert into `language` values("or", "or-IN",  "Oriya (India)", "", "");
insert into `language` values("or", "or",  "Oriya", "", "");
insert into `language` values("om", "om-ET",  "Oromo (Ethiopia)", "", "");
insert into `language` values("om", "om-KE",  "Oromo (Kenya)", "", "");
insert into `language` values("om", "om",  "Oromo", "", "");
insert into `language` values("ps", "ps-AF",  "Pashto (Afghanistan)", "", "");
insert into `language` values("ps", "ps",  "Pashto",  "", "");
insert into `language` values("fa", "fa-AF",  "Persian (Afghanistan)", "", "");
insert into `language` values("fa", "fa-IR",  "Persian (Iran)", "", "");
insert into `language` values("fa", "fa",  "Persian", "", "");
insert into `language` values("pl", "pl-PL",  "Polish (Poland)", "", "");
insert into `language` values("pl", "pl",  "Polish", "", "");
insert into `language` values("pt", "pt-BR",  "Portuguese (Brazil)", "", "");
insert into `language` values("pt", "pt-GW",  "Portuguese (Guinea-Bissau)", "", "");
insert into `language` values("pt", "pt-MZ",  "Portuguese (Mozambique)", "", "");
insert into `language` values("pt", "pt-PT",  "Portuguese (Portugal)", "", "");
insert into `language` values("pt", "pt",  "Portuguese", "", "");
insert into `language` values("pa", "pa-Arab",  "Punjabi (Arabic)", "", "");
insert into `language` values("pa", "pa-Arab-PK",  "Punjabi (Arabic, Pakistan)", "", "");
insert into `language` values("pa", "pa-Guru",  "Punjabi (Gurmukhi)", "", "");
insert into `language` values("pa", "pa-Guru-IN",  "Punjabi (Gurmukhi, India)", "", "");
insert into `language` values("pa", "pa",  "Punjabi", "", "");
insert into `language` values("ro", "ro-MD",  "Romanian (Moldova)", "", "");
insert into `language` values("ro", "ro-RO",  "Romanian (Romania)", "", "");
insert into `language` values("ro", "ro",  "Romanian", "", "");
insert into `language` values("rm", "rm-CH",  "Romansh (Switzerland)", "", "");
insert into `language` values("rm", "rm",  "Romansh", "", "");
insert into `language` values("rof", "rof-TZ",  "Rombo (Tanzania)", "", "");
insert into `language` values("rof", "rof",  "Rombo", "", "");
insert into `language` values("ru", "ru-MD",  "Russian (Moldova)", "", "");
insert into `language` values("ru", "ru-RU",  "Russian (Russia)", "", "");
insert into `language` values("ru", "ru-UA",  "Russian (Ukraine)", "", "");
insert into `language` values("ru", "ru",  "Russian", "", "");
insert into `language` values("rwk", "rwk-TZ",  "Rwa (Tanzania)", "", "");
insert into `language` values("rwk", "rwk",  "Rwa", "", "");
insert into `language` values("saq", "saq-KE",  "Samburu (Kenya)", "", "");
insert into `language` values("saq", "saq",  "Samburu", "", "");
insert into `language` values("sg", "sg-CF",  "Sango (Central African Republic)", "", "");
insert into `language` values("sg", "sg",  "Sango", "", "");
insert into `language` values("seh", "seh-MZ",  "Sena (Mozambique)", "", "");
insert into `language` values("seh", "seh",  "Sena", "", "");
insert into `language` values("sr", "sr-Cyrl",  "Serbian (Cyrillic)", "", "");
insert into `language` values("sr", "sr-Cyrl-BA",  "Serbian (Cyrillic, Bosnia and Herzegovina)", "", "");
insert into `language` values("sr", "sr-Cyrl-ME",  "Serbian (Cyrillic, Montenegro)", "", "");
insert into `language` values("sr", "sr-Cyrl-RS",  "Serbian (Cyrillic, Serbia)", "", "");
insert into `language` values("sr", "sr-Latn",  "Serbian (Latin)", "", "");
insert into `language` values("sr", "sr-Latn-BA",  "Serbian (Latin, Bosnia and Herzegovina)", "", "");
insert into `language` values("sr", "sr-Latn-ME",  "Serbian (Latin, Montenegro)", "", "");
insert into `language` values("sr", "sr-Latn-RS",  "Serbian (Latin, Serbia)", "", "");
insert into `language` values("sr", "sr",  "Serbian", "", "");
insert into `language` values("sn", "sn-ZW",  "Shona (Zimbabwe)", "", "");
insert into `language` values("sn", "sn",  "Shona", "", "");
insert into `language` values("ii", "ii-CN",  "Sichuan Yi (China)", "", "");
insert into `language` values("ii", "ii",  "Sichuan Yi", "", "");
insert into `language` values("si", "si-LK",  "Sinhala (Sri Lanka)", "", "");
insert into `language` values("si", "si",  "Sinhala", "", "");
insert into `language` values("sk", "sk-SK",  "Slovak (Slovakia)", "", "");
insert into `language` values("sk", "sk",  "Slovak", "", "");
insert into `language` values("sl", "sl-SI",  "Slovenian (Slovenia)", "", "");
insert into `language` values("sl", "sl",  "Slovenian", "", "");
insert into `language` values("xog", "xog-UG",  "Soga (Uganda)", "", "");
insert into `language` values("xog", "xog",  "Soga", "", "");
insert into `language` values("so", "so-DJ",  "Somali (Djibouti)", "", "");
insert into `language` values("so", "so-ET",  "Somali (Ethiopia)", "", "");
insert into `language` values("so", "so-KE",  "Somali (Kenya)", "", "");
insert into `language` values("so", "so-SO",  "Somali (Somalia)", "", "");
insert into `language` values("so", "so",  "Somali", "", "");
insert into `language` values("es", "es-AR",  "Spanish (Argentina)", "", "");
insert into `language` values("es", "es-BO",  "Spanish (Bolivia)", "", "");
insert into `language` values("es", "es-CL",  "Spanish (Chile)", "", "");
insert into `language` values("es", "es-CO",  "Spanish (Colombia)", "", "");
insert into `language` values("es", "es-CR",  "Spanish (Costa Rica)", "", "");
insert into `language` values("es", "es-DO",  "Spanish (Dominican Republic)", "", "");
insert into `language` values("es", "es-EC",  "Spanish (Ecuador)", "", "");
insert into `language` values("es", "es-SV",  "Spanish (El Salvador)", "", "");
insert into `language` values("es", "es-GQ",  "Spanish (Equatorial Guinea)", "", "");
insert into `language` values("es", "es-GT",  "Spanish (Guatemala)", "", "");
insert into `language` values("es", "es-HN",  "Spanish (Honduras)", "", "");
insert into `language` values("es", "es-419", "Spanish (Latin America)", "", "");
insert into `language` values("es", "es-MX",  "Spanish (Mexico)", "", "");
insert into `language` values("es", "es-NI",  "Spanish (Nicaragua)", "", "");
insert into `language` values("es", "es-PA",  "Spanish (Panama)", "", "");
insert into `language` values("es", "es-PY",  "Spanish (Paraguay)", "", "");
insert into `language` values("es", "es-PE",  "Spanish (Peru)", "", "");
insert into `language` values("es", "es-PR",  "Spanish (Puerto Rico)", "", "");
insert into `language` values("es", "es-ES",  "Spanish (Spain)", "", "");
insert into `language` values("es", "es-US",  "Spanish (United States)", "", "");
insert into `language` values("es", "es-UY",  "Spanish (Uruguay)", "", "");
insert into `language` values("es", "es-VE",  "Spanish (Venezuela)", "", "");
insert into `language` values("es", "es",     "Spanish", "", "");
insert into `language` values("sw", "sw-KE",  "Swahili (Kenya)", "", "");
insert into `language` values("sw", "sw-TZ",  "Swahili (Tanzania)", "", "");
insert into `language` values("sw", "sw",     "Swahili", "", "");
insert into `language` values("sv", "sv-FI",  "Swedish (Finland)", "", "");
insert into `language` values("sv", "sv-SE",  "Swedish (Sweden)", "", "");
insert into `language` values("sv", "sv",     "Swedish", "", "");
insert into `language` values("gsw", "gsw-CH",  "Swiss German (Switzerland)", "", "");
insert into `language` values("gsw", "gsw",   "Swiss German", "", "");
insert into `language` values("shi", "shi-Latn",  "Tachelhit (Latin)", "", "");
insert into `language` values("shi", "shi-Latn-MA",  "Tachelhit (Latin, Morocco)", "", "");
insert into `language` values("shi", "shi-Tfng",  "Tachelhit (Tifinagh)", "", "");
insert into `language` values("shi", "shi-Tfng-MA",  "Tachelhit (Tifinagh, Morocco)", "", "");
insert into `language` values("shi", "shi",  "Tachelhit", "", "");
insert into `language` values("dav", "dav-KE",  "Taita (Kenya)", "", "");
insert into `language` values("dav", "dav",  "Taita", "", "");
insert into `language` values("ta", "ta-IN",  "Tamil (India)", "", "");
insert into `language` values("ta", "ta-LK",  "Tamil (Sri Lanka)", "", "");
insert into `language` values("ta", "ta",  "Tamil",  "", "");
insert into `language` values("te", "te-IN",  "Telugu (India)", "", "");
insert into `language` values("te", "te",  "Telugu", "", "");
insert into `language` values("teo", "teo-KE",  "Teso (Kenya)", "", "");
insert into `language` values("teo", "teo-UG",  "Teso (Uganda)", "", "");
insert into `language` values("teo", "teo",  "Teso", "", "");
insert into `language` values("th", "th-TH",  "Thai (Thailand)", "ไทย", "");
insert into `language` values("th", "th",  "Thai", "ไทย", "");
insert into `language` values("bo", "bo-CN",  "Tibetan (China)", "", "");
insert into `language` values("bo", "bo-IN",  "Tibetan (India)", "", "");
insert into `language` values("bo", "bo",  "Tibetan", "", "");
insert into `language` values("ti", "ti-ER",  "Tigrinya (Eritrea)", "", "");
insert into `language` values("ti", "ti-ET",  "Tigrinya (Ethiopia)", "", "");
insert into `language` values("ti", "ti",  "Tigrinya", "", "");
insert into `language` values("to", "to-TO",  "Tonga (Tonga)", "", "");
insert into `language` values("to", "to",  "Tonga", "", "");
insert into `language` values("tr", "tr-TR",  "Turkish (Turkey)", "", "");
insert into `language` values("tr", "tr",  "Turkish", "", "");
insert into `language` values("uk", "uk-UA",  "Ukrainian (Ukraine)", "", "");
insert into `language` values("uk", "uk",  "Ukrainian", "", "");
insert into `language` values("ur", "ur-IN",  "Urdu (India)", "", "");
insert into `language` values("ur", "ur-PK",  "Urdu (Pakistan)", "", "");
insert into `language` values("ur", "ur",  "Urdu", "", "");
insert into `language` values("uz", "uz-Arab",  "Uzbek (Arabic)", "", "");
insert into `language` values("uz", "uz-Arab-AF",  "Uzbek (Arabic, Afghanistan)", "", "");
insert into `language` values("uz", "uz-Cyrl",  "Uzbek (Cyrillic)", "", "");
insert into `language` values("uz", "uz-Cyrl-UZ",  "Uzbek (Cyrillic, Uzbekistan)", "", "");
insert into `language` values("uz", "uz-Latn",  "Uzbek (Latin)", "", "");
insert into `language` values("uz", "uz-Latn-UZ",  "Uzbek (Latin, Uzbekistan)", "", "");
insert into `language` values("uz", "uz",  "Uzbek", "", "");
insert into `language` values("vi", "vi-VN",  "Vietnamese (Vietnam)", "Tiếng Việt", "");
insert into `language` values("vi", "vi",  "Vietnamese", "Tiếng Việt", "");
insert into `language` values("vun", "vun-TZ",  "Vunjo (Tanzania)", "", "");
insert into `language` values("vun", "vun",  "Vunjo", "", "");
insert into `language` values("cy", "cy-GB",  "Welsh (United Kingdom)", "", "");
insert into `language` values("cy", "cy",  "Welsh", "", "");
insert into `language` values("yo", "yo-NG",  "Yoruba (Nigeria)", "", "");
insert into `language` values("yo", "yo",  "Yoruba", "", "");
insert into `language` values("zu", "zu-ZA",  "Zulu (South Africa)", "", "");
insert into `language` values("zu", "zu",  "Zulu", "", "");
