UPDATE intl set en="Accepts", ru="Принять", fr="Accepte" WHERE key_code="﻿ACCEPTS";
UPDATE intl set en="Accordion", ru="Соглашение", fr="Accordéon" WHERE key_code="ACCORDION";
UPDATE intl set en="Your request has been successfully submitted", ru="Ваш запрос был успешно отправлен", fr="Votre requête a été transmise avec succès" WHERE key_code="ACK_REQ_OK";
UPDATE intl set en="Add", ru="Добавить", fr="Ajouter" WHERE key_code="ADD";
UPDATE intl set en="Address", ru="Адрес", fr="Adresse" WHERE key_code="ADDRESS";
UPDATE intl set en="Create a project site", ru="Создать сайт", fr="Créer un site projet" WHERE key_code="ADD_HUB";
UPDATE intl set en="Add a mate", ru="Добавить друга", fr="Ajouter un collaborteur" WHERE key_code="ADD_HUBER";
UPDATE intl set en="Create a project site", ru="Создать сайт", fr="Créer un site de projet" WHERE key_code="ADD_HUB_SITE";
UPDATE intl set en="Add a new layer", ru="Добавить новый слой", fr="Ajouter un nouveau calque" WHERE key_code="ADD_LAYER";
UPDATE intl set en="Create a site", ru="Создать сайт", fr="Créer un site" WHERE key_code="ADD_SITE";
UPDATE intl set en="Add a new slide", ru="Добавить новый слайд", fr="Ajouter une nouvelle planche" WHERE key_code="ADD_SLIDE";
UPDATE intl set en="Add user account", ru="Добавить пользователя", fr="Créer un compte utilisateur" WHERE key_code="ADD_USER";
UPDATE intl set en="Adjust", ru="Настроить", fr="Régler" WHERE key_code="ADJUST";
UPDATE intl set en="Administrators only", ru="Только для администратора", fr="Accès réservé aux administrateurs" WHERE key_code="ADMIN_ACCESS";
UPDATE intl set en="{0} is the hub {1} administrator. If you want to remove this drumate, you must first widthdraw his privilege.", ru="{0} - администратор хаба {1}. Если вы хотите удалить этого друга, сначала освободите его от полномочий.", fr="{0} est un administrateur du hub {1}. Si vous souhaitez retirer ce drumate, vous devez lui otez d'abord ce privilège." WHERE key_code="ADMIN_REMOVAL_WARN";
UPDATE intl set en="Agenda", ru="Повестка дня", fr="Agenda" WHERE key_code="AGENDA";
UPDATE intl set en="Site alias address", ru="Псевдоним сайта", fr="Adresse alias du site" WHERE key_code="ALIAS_SITE";
UPDATE intl set en="Align", ru="Выровнить", fr="Aligner" WHERE key_code="ALIGN";
UPDATE intl set en="Alignment", ru="Выравнивание", fr="Alignement" WHERE key_code="ALIGNMENT";
UPDATE intl set en="Horizontal alignment", ru="Выравнивание по горизонтали", fr="Alignement horizontal" WHERE key_code="ALIGN_H";
UPDATE intl set en="Vertical alignment", ru="Выравнивание по вертикали", fr="Alignement vertical" WHERE key_code="ALIGN_V";
UPDATE intl set en="All files", ru="Все файлы", fr="Tous les fichiers" WHERE key_code="ALL_FILES";
UPDATE intl set en="All messages", ru="Все сообщения", fr="Tous les messages" WHERE key_code="ALL_MSG";
UPDATE intl set en="All spaces", ru="Все места", fr="Tous les espaces" WHERE key_code="ALL_SPACES";
UPDATE intl set en="Your session has already been open", ru="Ваша сессия уже началась", fr="Votre session est déjà ouverte" WHERE key_code="ALREADY_CONNECTED";
UPDATE intl set en="{0} is already the hub member", ru="Пользователь уже является членом хаба. ", fr="{0} est déjà membre du hub" WHERE key_code="ALREADY_MEMBER";
UPDATE intl set en="Is already selected", ru="Уже выбрано", fr="Est déjà sélectionné(e)" WHERE key_code="ALREADY_SELECTED";
UPDATE intl set en="Analytics", ru="Аналитика", fr="Analyse" WHERE key_code="ANALYTICS";
UPDATE intl set en="Agenda", ru="Повестка дня", fr="Agenda" WHERE key_code="ANGENDA";
UPDATE intl set en="Animate the first slide", ru="Оживить первый слайд", fr="Animer la première planche" WHERE key_code="ANIMATEFIRSTSLIDE";
UPDATE intl set en="Animation", ru="Анимация", fr="Animation" WHERE key_code="ANIMATION";
UPDATE intl set en="Animate at start", ru="Анимировать в начале", fr="Animer au démarrage" WHERE key_code="ANIM_AT_START";
UPDATE intl set en="Animated card", ru="Анимированная открытка", fr="Carte animée" WHERE key_code="ANIM_CARD";
UPDATE intl set en="Animation duration, in seconds", ru="Время анимации в секундах", fr="Durée d'animation, en secondes" WHERE key_code="ANIM_DURATION";
UPDATE intl set en="Animation options", ru="Параметры анимации", fr="Options d'animation" WHERE key_code="ANIM_OPTIONS";
UPDATE intl set en="Anonymous", ru="Анонимно", fr="Anonyme" WHERE key_code="ANONYMOUS";
UPDATE intl set en="API", ru="API", fr="API" WHERE key_code="API";
UPDATE intl set en="Appearance", ru="Оформление", fr="Apparence" WHERE key_code="APPEARANCE";
UPDATE intl set en="Apply", ru="Применить", fr="Appliquer" WHERE key_code="APPLY";
UPDATE intl set en="Are you sure?", ru="Вы уверены?", fr="Etes-vous sûr(e)?" WHERE key_code="ARE_YOU_SURE";
UPDATE intl set en="Audio", ru="Музыка", fr="Audio" WHERE key_code="AUDIO";
UPDATE intl set en="Auto pause slideshow", ru="Слайдшоу с автопаузой", fr="Pause auto des planches" WHERE key_code="AUTOPAUSESLIDESHOW";
UPDATE intl set en="Autoplay", ru="Автоматическое проигрывание", fr="Démarrage automatique" WHERE key_code="AUTOPLAY";
UPDATE intl set en="Auto play videos", ru="Автоматическое проигрование видео", fr="Lecture auto de videos" WHERE key_code="AUTOPLAYVIDEOS";
UPDATE intl set en="Auto start", ru="Автоматический старт", fr="Lancement auto" WHERE key_code="AUTOSTART";
UPDATE intl set en="Automatic positionning box", ru="Автоматическое позиционирование блока", fr="Bloc à positionnement automatique" WHERE key_code="AUTO_BOX";
UPDATE intl set en="Automatic positioning container", ru="Автоматическое позиционирование контейнера", fr="Conteneur à placement automatique" WHERE key_code="AUTO_CONTAINER";
UPDATE intl set en="Back", ru="Назад ", fr="Verso" WHERE key_code="BACK";
UPDATE intl set en="Background", ru="Фон", fr="Fond" WHERE key_code="BACKGROUND";
UPDATE intl set en="Background color", ru="Заливка фона", fr="Couleur du fond" WHERE key_code="BACKGROUND-COLOR";
UPDATE intl set en="Back face", ru="Задняя сторона", fr="Face arrière" WHERE key_code="BACK_FACE";
UPDATE intl set en="Your browser seems not to be working for uploading file. plase, use firefox, chrome or a html5 browser.", ru="Похоже, что ваш браузер не справляется с загрузкой файла. Пожалуйста, используйте браузеры Firefox, Google Chrome или HTML5.", fr="Votre navigateur n'a pas les fonctions requises pour envoyer de fichiers. utilsez firefox, chrome ou un navigateur html5" WHERE key_code="BAD_UA";
UPDATE intl set en="Banner", ru="Баннер ", fr="Bannière" WHERE key_code="BANNER";
UPDATE intl set en="before deletion", ru="перед удалением", fr="avant suppression" WHERE key_code="BEFORE_REMOVAL";
UPDATE intl set en="Background color", ru="Заливка фона", fr="Couleur de fond" WHERE key_code="BG_COLOR";
UPDATE intl set en="Background image", ru="Фоновая картинка", fr="Image de fond" WHERE key_code="BG_IMAGE";
UPDATE intl set en="Blogs", ru="Блоги", fr="Blogs" WHERE key_code="BLOGS";
UPDATE intl set en="Blur", ru="Размытие", fr="Flou" WHERE key_code="BLUR";
UPDATE intl set en="Bold", ru="Жирный", fr="Gras" WHERE key_code="BOLD";
UPDATE intl set en="Border", ru="Границы", fr="Bordure" WHERE key_code="BORDER";
UPDATE intl set en="Borders styles", ru="Стиль границ", fr="Styles de bordures" WHERE key_code="BORDERS_STYLES";
UPDATE intl set en="Border color", ru="Цвет границ", fr="Couleur de bordure" WHERE key_code="BORDER_COLOR";
UPDATE intl set en="Border thickness", ru="Ширина границ", fr="Epaisseur de bordure" WHERE key_code="BORDER_THICKNESS";
UPDATE intl set en="Bottom", ru="Нижняя часть экрана", fr="Bas" WHERE key_code="BOTTOM";
UPDATE intl set en="BoÃ®te", ru="Блок", fr="Box" WHERE key_code="BOX";
UPDATE intl set en="Brightness", ru="Яркость", fr="Luminosité" WHERE key_code="BRIGHTNESS";
UPDATE intl set en="Button", ru="Кнопка", fr="Bouton" WHERE key_code="BUTTON";
UPDATE intl set en="Toggle button", ru="Кнопка-переключатель", fr="Bouton poussoire" WHERE key_code="BUTTON_TOGGLE";
UPDATE intl set en="Cancel", ru="Отмена", fr="Annuler" WHERE key_code="CANCEL";
UPDATE intl set en="Operation canceled!", ru="Действие отменено", fr="Opération annulée!" WHERE key_code="CANCELED";
UPDATE intl set en="Caption", ru="Подпись", fr="Legender" WHERE key_code="CAPTION";
UPDATE intl set en="Center", ru="Середина", fr="Centre" WHERE key_code="CENTER";
UPDATE intl set en="Horizontal center", ru="Горизонтальный центр", fr="Centre horizontal" WHERE key_code="CENTER_H";
UPDATE intl set en="Vertical center", ru="Вертиканый центр", fr="Centre vertical" WHERE key_code="CENTER_V";
UPDATE intl set en="Changes log", ru="Изменить логин", fr="Historique des modifications" WHERE key_code="CHANGES_LOG";
UPDATE intl set en="You have requested to reset your password. Please, enter the new one here below", ru="Вы хотите сбросить пароль. Пожалуйства, введите новый пароль ниже.", fr="Vous avez demandé à réinitialier votre mot de passe. Veuillez le saisir ci-après." WHERE key_code="CHANGE_PASSWORD";
UPDATE intl set en="Chart ({0})", ru="Диаграмма ({0})", fr="Graphique ({0})" WHERE key_code="CHART";
UPDATE intl set en="Area", ru="Область", fr="Zone remplie" WHERE key_code="CHART_AREA";
UPDATE intl set en="Bar chart", ru="Линейная диаграмма", fr="Histogramme" WHERE key_code="CHART_BAR";
UPDATE intl set en="Donut", ru="Круговая диаграмма", fr="Donut" WHERE key_code="CHART_DONUT";
UPDATE intl set en="Pie chart", ru="Круговая диаграмма", fr="Camembert" WHERE key_code="CHART_PIE";
UPDATE intl set en="Chart types", ru="Виды диаграмм", fr="Types de graphique" WHERE key_code="CHART_TYPE";
UPDATE intl set en="Chat", ru="Чат", fr="Chat" WHERE key_code="CHAT";
UPDATE intl set en="Check", ru="Проверить", fr="Vérification" WHERE key_code="CHECK";
UPDATE intl set en="Checkbox", ru="Флажок", fr="Case à cocher" WHERE key_code="CHECKBOX";
UPDATE intl set en="Please, chose the removal option (freeze or definitive)", ru="Пожалуйста, выберите вариант удаления (блокировать или удалить полностью)", fr="Veuillez choisir l'option de suppression (gel ou définitif)" WHERE key_code="CHOOSE_DEL_OPT";
UPDATE intl set en="Please, select the destination directory!", ru="Пожалуйста, выберите место назначения.", fr="Veuillez choisir le répertoire de destination!" WHERE key_code="CHOOSE_DEST_DIR";
UPDATE intl set en="Choose your language", ru="Выберите язык", fr="Sélectionnez votre langue" WHERE key_code="CHOOSE_YOUR_LANG";
UPDATE intl set en="Click here", ru="Нажмите здесь", fr="Cliquez ici" WHERE key_code="CLICK_HERE";
UPDATE intl set en="Click here to start", ru="Нажмите, чтобы начать", fr="Cliquez ici pour commencer" WHERE key_code="CLICK_TO_START";
UPDATE intl set en="Close", ru="Закрыть", fr="Fermer" WHERE key_code="CLOSE";
UPDATE intl set en="Name", ru="Имя", fr="Nom" WHERE key_code="CNAME";
UPDATE intl set en="Color", ru="Цвет", fr="Couleur" WHERE key_code="COLOR";
UPDATE intl set en="Incoming color", ru="Цвет входа анимации", fr="Couleur d'entrée" WHERE key_code="COLORIN";
UPDATE intl set en="Outgoing color", ru="Цвет выхода анимации", fr="Couleur de sortie" WHERE key_code="COLOROUT";
UPDATE intl set en="Coming soon", ru="Скоро появится", fr="Bientôt disponible" WHERE key_code="COMING_SOON";
UPDATE intl set en="Comment", ru="Комментировать", fr="Commenter" WHERE key_code="COMMENT";
UPDATE intl set en="Comments", ru="Комментарии", fr="Commentaire" WHERE key_code="COMMENTS";
UPDATE intl set en="Comments thread, waiting for playing signal...", ru="Ветка комментариев, ожидается сигнал воспроизведения", fr="Fil de commentaire, en attente d'un signal de lecture..." WHERE key_code="COMMENTS_IDLE";
UPDATE intl set en="Communities", ru="Группы", fr="Communautés" WHERE key_code="COMMUNITIES";
UPDATE intl set en="You have to choose a community to post to your message!", ru="Выберите сообщество, чтобы опубликовать сообщение!", fr="Vous devez choisir la communauté destinataire de votre message!" WHERE key_code="COMMUNITY_REQUIRED";
UPDATE intl set en="Confirm *{0}*?", ru="Подтвердить *{0}*?", fr="Confirmez *{0}*?" WHERE key_code="CONFIRM";
UPDATE intl set en="Operation confirmed!", ru="Действие подтверждено!", fr="Opération confirmée!" WHERE key_code="CONFIRMED";
UPDATE intl set en="Do you confirm this action?", ru="Вы подтверждаете действие?", fr="Confirmez-vous cette action?" WHERE key_code="CONFIRM_ACTION";
UPDATE intl set en="Are you sure to cancel ?", ru="Вы уверены, что хотите отменить?", fr="Etes-vous sûr(e) de vouloir annuler?" WHERE key_code="CONFIRM_CANCEL";
UPDATE intl set en="The download size is {0}. Are you sure ?", ru="Размер файла загрузки {0}. Вы уверены?", fr="La taille du téléchargement est de {0}. En êtes-vous sûr?" WHERE key_code="CONFIRM_DOWNLOAD";
UPDATE intl set en="Are you sure you want to quit this pgae ?", ru="Вы уверены, что хотите покинуть эту страницу?", fr="Etes-vous sûr de vouloir quitter cette page ?" WHERE key_code="CONFIRM_QUIT";
UPDATE intl set en="This element has already been deleted. Do you want to retrieve it?", ru="Этот элемент был удалён. Вы хотите вернуть его?", fr="Cet élément a déjà été supprimé. Voulez-vous le restituer?" WHERE key_code="CONFIRM_RETRIEVE";
UPDATE intl set en="Contact us", ru="Свяжитесь с нами", fr="Contactez-nous" WHERE key_code="CONTACT";
UPDATE intl set en="Please, enter your message in the form below and we will reply as soon as possible.", ru="Пожалуйста, оставьте сообщение в форме ниже, и мы ответим вам как можно скорее. ", fr="Veuillez laisser votre message dans le formulaire ci-dessous. nous vous répondrons dès que possible." WHERE key_code="CONTACT_MSG";
UPDATE intl set en="Fit in container", ru="Пожалуйста, введите сообщение в форме ниже и мы от", fr="Ajusté au conteneur" WHERE key_code="CONTAINED";
UPDATE intl set en="Container", ru="Вставить в контейнер", fr="Conteneur" WHERE key_code="CONTAINER";
UPDATE intl set en="Float container", ru="Контейнер", fr="Conteneur flottant" WHERE key_code="CONTAINER_FLOAT";
UPDATE intl set en="Footer container", ru="Нижний контейнер", fr="Conteneur pied de page" WHERE key_code="CONTAINER_FOOTER";
UPDATE intl set en="Horizontal container", ru="Горизонтальный контейнер", fr="Conteneur horizontal" WHERE key_code="CONTAINER_HORIZONTAL";
UPDATE intl set en="Horizontal flow container. must be put in the one that flows vertically.", ru="Горизонтальный контейнер. Его нужно вставить в вертикальный.", fr="Containeur à empilement hoizontal. Doit être placé dans celui à empilement vertical" WHERE key_code="CONTAINER_H_TIP";
UPDATE intl set en="Root container", ru="Корневой контейнер", fr="Conteneur racine" WHERE key_code="CONTAINER_ROOT";
UPDATE intl set en="An horizontal container must be included within the one of vertical type, and vis-versa", ru="Горизонтальный контейнер должен быть внутри вертикального или наоборот.", fr="Un container de type horizontal doit être deposé dans celui de type vertical et vice-versa" WHERE key_code="CONTAINER_RULES";
UPDATE intl set en="Vertical container", ru="Вертикальный контейнер", fr="Conteneur vertical" WHERE key_code="CONTAINER_VERTICAL";
UPDATE intl set en="Vertical flow container. must be put in the one that flows horizontally.", ru="Вертикальный контейнер. Его нужно вставить в горизонтальный.", fr="Containeur à empilement vertical. doit être placé dans celui à empilement horizontal" WHERE key_code="CONTAINER_V_TIP";
UPDATE intl set en="The inputs contains unauthorized values", ru="Введенные данные содержат неразрешённые значения. ", fr="Les valeurs saisies contiennent des valeurs non autorisées" WHERE key_code="CONTAIN_FORBIDEN_CHARS";
UPDATE intl set en="Content", ru="Содержание", fr="Contenu" WHERE key_code="CONTENT";
UPDATE intl set en="Contextmenu", ru="Контекстное меню", fr="Menu contextuel" WHERE key_code="CONTEXTMENU";
UPDATE intl set en="Contrast", ru="Контраст", fr="Contraste" WHERE key_code="CONTRAST";
UPDATE intl set en="Contributor", ru="Помощник", fr="Contributeur" WHERE key_code="CONTRIBUTOR";
UPDATE intl set en="For convenience and safety reasons, connection to drumee.com requires cokkies to be activated on your web navigator.", ru="Для удобства и безпасности при использовании  drumee.com нужно включить cokkies", fr="Pour des raisons de confort et de securité, la connexion a drumee.com nécessite l'activation des cookies votre navigateur." WHERE key_code="COOKIES_REQUIRED";
UPDATE intl set en="Copy", ru="Копировать", fr="Copier" WHERE key_code="COPY";
UPDATE intl set en="Copy link", ru="Скопировать ссылку", fr="Copier le lien" WHERE key_code="COPYLINK";
UPDATE intl set en="Copy style", ru="Скопировать стайл", fr="Copier le style" WHERE key_code="COPY_STYLE";
UPDATE intl set en="Costumized CSS", ru="Настраиваемый CSS", fr="CSS personalisées" WHERE key_code="COSTUM_CSS";
UPDATE intl set en="Create your Drumee account", ru="Создать аккаунт в Drumee", fr="Créez votre compte Drumee" WHERE key_code="CREATE_ACCOUNT";
UPDATE intl set en="Crop", ru="Обрезать", fr="Rogner" WHERE key_code="CROP";
UPDATE intl set en="Native CSS classes", ru="Стандратные классы", fr="Classes CSS natives" WHERE key_code="CSS_CLASSES";
UPDATE intl set en="CSS files", ru="Файлы СSS", fr="Fichiers CSS" WHERE key_code="CSS_FILES";
UPDATE intl set en="Customize", ru="Персонализировать", fr="Personnaliser" WHERE key_code="CUSTOMISE";
UPDATE intl set en="Data not found !", ru="Данные не найдены!", fr="Aucune donnée n'a été renseignée!" WHERE key_code="DATA_NOT_FOUND";
UPDATE intl set en="Please, data are requied to perform your request.", ru="Пожалуйста, введите данные для выполнения вашего запроса.", fr="Les données sont nécessaires à l'exécution de votre requête." WHERE key_code="DATA_REQUIRED";
UPDATE intl set en="Day(s)", ru="День(дни)", fr="Jour(s)" WHERE key_code="DAYS";
UPDATE intl set en="You can use drag and drop fonctionnality to share you files", ru="Вы можете использовать область перетаскивания чтобы делиться своимми файлами", fr="Vous pouvez utiliser la fonction glisser-déposer pour partager vos fichiers" WHERE key_code="DD_INDICATION";
UPDATE intl set en="Deep link", ru="Глубинная ссылка", fr="Lien profond" WHERE key_code="DEEPLINK";
UPDATE intl set en="Default permission", ru="Стандартное разрешение", fr="Permission par défaut" WHERE key_code="DEFAULT_PERMISSION";
UPDATE intl set en="Exposure duration", ru="Продолжительность представления", fr="Durée d'exposition" WHERE key_code="DELAY";
UPDATE intl set en="Exposure duration", ru="Продолжительность представления", fr="Durée d'exposition" WHERE key_code="DELAYIN";
UPDATE intl set en="Delete", ru="Удалить", fr="Supprimer" WHERE key_code="DELETE";
UPDATE intl set en="Description", ru="Описание", fr="Description" WHERE key_code="DESCRIPTION";
UPDATE intl set en="Drag and drop here components the page you want to set up", ru="Перетащите сюда объекты сайта, которые вы хотите использовать", fr="Faîtes glisser et déposer ici les éléments de votre page" WHERE key_code="DESIGN_PAGE_TIP";
UPDATE intl set en="Desktop", ru="Компьютер", fr="Ordinateur" WHERE key_code="DESKTOP";
UPDATE intl set en="Device type", ru="Тип устройства", fr="Type de terminal" WHERE key_code="DEVICE_TYPE";
UPDATE intl set en="Developper mode", ru="Режим разработчика", fr="Mode développeur" WHERE key_code="DEVMODE";
UPDATE intl set en="It is not (yet) allowed to attach a whole directory", ru="Пока нет разрешения на прикрепление всего каталога. ", fr="Il n'est pas (encore) permis de joindre un réprtoire." WHERE key_code="DIR_NOT_ALLOWED";
UPDATE intl set en="Disable the hub", ru="Отключить", fr="Désactiver le hub" WHERE key_code="DISABLE_HUB";
UPDATE intl set en="D-mail", ru="Drumee-mail ", fr="D-mail" WHERE key_code="DMAIL";
UPDATE intl set en="Document", ru="Документ", fr="Document" WHERE key_code="DOCUMENT";
UPDATE intl set en="Documents", ru="Документы", fr="Documents" WHERE key_code="DOCUMENTS";
UPDATE intl set en="Domaine name", ru="Доменное имя", fr="Nom de domaine" WHERE key_code="DOMAINE_NAME";
UPDATE intl set en="Don't know", ru="Не знаю.", fr="Ne sais pas" WHERE key_code="DONTKNOW";
UPDATE intl set en="Download", ru="Загрузить", fr="Télécharger" WHERE key_code="DOWNLOAD";
UPDATE intl set en="Download all", ru="Загрузить всё", fr="Télécharger tout" WHERE key_code="DOWNLOAD_ALL";
UPDATE intl set en="Draft", ru="Черновик", fr="Brouillon" WHERE key_code="DRAFT";
UPDATE intl set en="Drawing", ru="Рисунок", fr="Dessin" WHERE key_code="DRAW";
UPDATE intl set en="Documents", ru="Документы", fr="Documents" WHERE key_code="DUCUMENTS";
UPDATE intl set en="Duplicate", ru="Создать дубликат", fr="Dupliquer" WHERE key_code="DUPLICATE";
UPDATE intl set en="Durations", ru="Трафик", fr="Durée" WHERE key_code="DURATION";
UPDATE intl set en="Incoming duration", ru="Входящий трафик", fr="Durée d'entrée" WHERE key_code="DURATIONIN";
UPDATE intl set en="Outgoing duration", ru="Исходящий трафик", fr="Durée de sortie" WHERE key_code="DURATIONOUT";
UPDATE intl set en="Each side", ru="Каждая сторона", fr="Chaque côté" WHERE key_code="EACH_SIDE";
UPDATE intl set en="Easing", ru="Плавность", fr="Easing" WHERE key_code="EASE";
UPDATE intl set en="Easing in", ru="Easing in", fr="Easing d'entrée" WHERE key_code="EASINGIN";
UPDATE intl set en="Easing out", ru="Easing out", fr="Easing de sortie" WHERE key_code="EASINGOUT";
UPDATE intl set en="Edit", ru="Редактировать", fr="Editer" WHERE key_code="EDIT";
UPDATE intl set en="E-mail", ru="E-mail", fr="E-mail" WHERE key_code="EMAIL";
UPDATE intl set en="Confirm e-mail", ru="Подтвердить e-mail", fr="Confirmation e-mail" WHERE key_code="EMAIL_CHECK";
UPDATE intl set en="E-mail or ident", ru="E-mail или логин", fr="E-mail ou dentidiant" WHERE key_code="EMAIL_OR_ID";
UPDATE intl set en="Empty", ru="Пусто", fr="Vider" WHERE key_code="EMPTY";
UPDATE intl set en="You are attempting to upload an empty file !", ru="Вы пытаетесь загрузить пустой файл!", fr="Le fichier que vous voulez envoyer est vide!" WHERE key_code="EMPTY_FILE";
UPDATE intl set en="English", ru="Английский", fr="Anglais" WHERE key_code="en";
UPDATE intl set en="Type your answer here", ru="Введите ответ на вопрос", fr="Tapez votre réponse ici" WHERE key_code="ENTER_ANSWER";
UPDATE intl set en="Enter your e-mail address...", ru="Введите e-mail ", fr="Entrez votre adresse e-mail..." WHERE key_code="ENTER_EMAIL";
UPDATE intl set en="Type your question here", ru="Введите вопрос", fr="Tapez votre question ici" WHERE key_code="ENTER_QUESTION";
UPDATE intl set en="Type your text here", ru="Введите текст", fr="Tapez votre texte ici" WHERE key_code="ENTER_TEXT";
UPDATE intl set en="Available text entry", ru="Ввод текста", fr="Champ de valeur disponible" WHERE key_code="ENTRY_AVAILABLE";
UPDATE intl set en="English", ru="Английский", fr="Anglais" WHERE key_code="en_GB";
UPDATE intl set en="English", ru="Английский", fr="Anglais" WHERE key_code="en_US";
UPDATE intl set en="Erase", ru="Стереть", fr="Effacer" WHERE key_code="ERASE";
UPDATE intl set en="An error has occured while attemting to fetch the layout", ru="Возникла ошибка при попытке извлечь макет.", fr="Une erreur est survenue en tentant d'obtenir le layout" WHERE key_code="ERROR_LAYOUT_FETCH";
UPDATE intl set en="A network error has occured", ru="Проблема с Интернет-соединением.", fr="Une errer réseau est survenue" WHERE key_code="ERROR_NETWORK";
UPDATE intl set en="The server has encountered an error", ru="Произошла ошибка сервера.", fr="Le serveur a rencontré une erreur" WHERE key_code="ERROR_SERVER";
UPDATE intl set en="Syntax error", ru="Синтаксическая ошибка", fr="Erreur de syntaxe" WHERE key_code="ERROR_SYNTAX";
UPDATE intl set en="Ident required", ru="Требуется ID", fr="Identifiant requis" WHERE key_code="ERR_ID_REQUIRED";
UPDATE intl set en="Missing data", ru="Отсутствие данных", fr="Données manquantes" WHERE key_code="ERR_NO_PIPE";
UPDATE intl set en="This area only accepts images", ru="Сюда можно вставлять только картинки", fr="Cette zone accepte seulement les images" WHERE key_code="ERR_ONLY_IMG";
UPDATE intl set en="Wrong request", ru="Неверный запрос", fr="Requête erronnéee" WHERE key_code="ERR_REQUEST";
UPDATE intl set en="Expand", ru="Расширить", fr="Développer" WHERE key_code="EXPAND";
UPDATE intl set en="External links", ru="Внешние ссылки", fr="Liens externes" WHERE key_code="EXT_LINKS";
UPDATE intl set en="Fade in", ru="Постепенное появление", fr="Fondu d'entrée" WHERE key_code="FADEIN";
UPDATE intl set en="Fade out", ru="Постепенное исчезновение", fr="Fondu de sortie" WHERE key_code="FADEOUT";
UPDATE intl set en="Female", ru="Жен", fr="Femme" WHERE key_code="FEMALE";
UPDATE intl set en="Color", ru="Цвет", fr="Couleur" WHERE key_code="FG_COLOR";
UPDATE intl set en="Field", ru="Поле", fr="Champ" WHERE key_code="FIELD";
UPDATE intl set en="Files", ru="Файлы", fr="Fichiers" WHERE key_code="FILES";
UPDATE intl set en="Your file has been deleted.", ru="Файл удалён. ", fr="Vos fichiers ont bien été effacés" WHERE key_code="FILES_DELETED";
UPDATE intl set en="Your file has not been deleted!", ru="Файл не удалён!", fr="Vos fichiers n'ont pas été effacés!" WHERE key_code="FILES_NOT_DELETED";
UPDATE intl set en="This function accepts at most {0} file(s).", ru="Эту функцию принимают не больше {0} файлов.", fr="Cette fonction accepte au plus {0} fichiers(s)" WHERE key_code="FILES_NUM_LIMIT";
UPDATE intl set en="Firstname", ru="Имя", fr="Prénom" WHERE key_code="FIRSTNAME";
UPDATE intl set en="First slide", ru="Первый слайд", fr="Première Planche" WHERE key_code="FIRSTSLIDE";
UPDATE intl set en="Flexible width", ru="Настраиваемая ширина", fr="Largeur flexible" WHERE key_code="FLEX_WIDTH";
UPDATE intl set en="Horizontal flow", ru="Горизонтальное направление", fr="Ecoulement horizontal" WHERE key_code="FLOW_H";
UPDATE intl set en="Vertical flow", ru="Вертикальное направление", fr="Ecoulement vertical" WHERE key_code="FLOW_V";
UPDATE intl set en="Folder", ru="Папка", fr="Dossier" WHERE key_code="FOLDER";
UPDATE intl set en="Font", ru="Шрифт", fr="Police" WHERE key_code="FONT";
UPDATE intl set en="Font family", ru="Семейтво шрифтов", fr="Famille de police" WHERE key_code="FONT_FAMILY";
UPDATE intl set en="Font size", ru="Размер шрифта", fr="Taille de police" WHERE key_code="FONT_SIZE";
UPDATE intl set en="Font style", ru="Стиль шрифта", fr="Style de police" WHERE key_code="FONT_STYLE";
UPDATE intl set en="Play for loops count", ru="Прокрутить до конца циклов", fr="Lire pour n boucles" WHERE key_code="FORCELOOPNUM";
UPDATE intl set en="Form", ru="Форма", fr="Formulaire" WHERE key_code="FORM";
UPDATE intl set en="Card", ru="Карта", fr="Carte" WHERE key_code="FORMAT_CARD";
UPDATE intl set en="Definition format", ru="Формат определения", fr="Format de définition" WHERE key_code="FORMAT_DEFITION";
UPDATE intl set en="Orginal", ru="Оригинал", fr="Original" WHERE key_code="FORMAT_ORIG";
UPDATE intl set en="Slide", ru="Слайд ", fr="Slide" WHERE key_code="FORMAT_SLIDE";
UPDATE intl set en="Thumbnail", ru="Миниатюра", fr="Miniature" WHERE key_code="FORMAT_THUMB";
UPDATE intl set en="Forms", ru="Формы", fr="Formulaires" WHERE key_code="FORMS";
UPDATE intl set en="Contact form", ru="Форма связи", fr="Formulaire de contact" WHERE key_code="FORM_CONTACT";
UPDATE intl set en="Create a form", ru="Создать форму", fr="Créer un formulaire" WHERE key_code="FORM_CREATE";
UPDATE intl set en="E-mail form", ru="Форма e-mail", fr="Formulaire e-mail" WHERE key_code="FORM_EMAIL";
UPDATE intl set en="Entry field", ru="Поле ввода", fr="Champ de saisie" WHERE key_code="FORM_ENTRY";
UPDATE intl set en="Identity form", ru="Форма ID", fr="Formulaire d'identité" WHERE key_code="FORM_IDENTITY";
UPDATE intl set en="Poll form", ru="Форма опроса ", fr="Formulaire de sondage" WHERE key_code="FORM_POLL";
UPDATE intl set en="Please, fill in the from below", ru="Пожалуйста, заполните форму ниже.", fr="Veuillez remplir les champs ci-dessous" WHERE key_code="FORM_PROMPT";
UPDATE intl set en="Sign on form", ru="Форма регистрации", fr="Formulaire d'inscription" WHERE key_code="FORM_REGISTER";
UPDATE intl set en="Thank you for joining Drumee, please enter a password to validate your account.", ru="Спасибо, что вы теперь с Drumee! Пожалуйста, введите пароль.", fr="Merci d'avoir rejoint Drumee, veuillez saisir un mot de passe pour votre compte." WHERE key_code="FORM_SIGNON";
UPDATE intl set en="French", ru="Французский", fr="Français" WHERE key_code="fr";
UPDATE intl set en="Free positioning container", ru="Свободное позиционирование контейнера", fr="Conteneur à placement libre" WHERE key_code="FREE_CONTAINER";
UPDATE intl set en="French", ru="Французский", fr="Français" WHERE key_code="FRENCH";
UPDATE intl set en="Front", ru="Передняя сторона", fr="Recto" WHERE key_code="FRONT";
UPDATE intl set en="Front face", ru="Передняя сторона", fr="Face avant" WHERE key_code="FRONT_FACE";
UPDATE intl set en="French", ru="Французский", fr="Français" WHERE key_code="fr_FR";
UPDATE intl set en="Full name", ru="Полное имя", fr="Nom complet" WHERE key_code="FULLNAME";
UPDATE intl set en="Full width", ru="Полная ширина", fr="Pleine largeur" WHERE key_code="FULL_WIDTH";
UPDATE intl set en="Special effects", ru="Специальные эффекты", fr="Effets spéciaux" WHERE key_code="FX";
UPDATE intl set en="{0}'s images gallery", ru="Галерея картинок {0}", fr="Galerie d'images de {0}" WHERE key_code="GALLERY";
UPDATE intl set en="Gender", ru="Пол", fr="Civilité" WHERE key_code="GENDER";
UPDATE intl set en="General", ru="Основные", fr="Généralité" WHERE key_code="GENERAL";
UPDATE intl set en="Gb", ru="Гб", fr="Go" WHERE key_code="GIGA_BYTE";
UPDATE intl set en="Global background color", ru="Глобальная заливка фона", fr="Couleur de fond globale" WHERE key_code="GLOBALBGCOLOR";
UPDATE intl set en="Global background image", ru="Глобальная картинка фона", fr="Image de fond globale" WHERE key_code="GLOBALBGIMAGE";
UPDATE intl set en="Global settings", ru="Глобальные настройки ", fr="Paramètres globaux" WHERE key_code="GLOBAL_SETTINGS";
UPDATE intl set en="Yes, I've got it", ru="Да, у меня есть.", fr="Oui, j'ai compris." WHERE key_code="GOT_IT";
UPDATE intl set en="Group", ru="Группировать", fr="Grouper" WHERE key_code="GROUP";
UPDATE intl set en="Greensock animation", ru="Анимация Greensock", fr="Animation Greensock" WHERE key_code="GS_ANIM";
UPDATE intl set en="Guest", ru="Гость", fr="Invité(e)" WHERE key_code="GUEST";
UPDATE intl set en="Hash tag", ru="Теги", fr="Hash tag" WHERE key_code="HASH_TAG";
UPDATE intl set en="Has been already moved!", ru="Уже перемещён. ", fr="A déjà été déplacé!" WHERE key_code="HAS_BEEN_MOVED";
UPDATE intl set en="{0} has been successfully saved", ru="{0} успешно сохранен", fr="{0} a été enregistré avec succès" WHERE key_code="HAS_BEEN_SAVED";
UPDATE intl set en="Heading", ru="Заглавие", fr="Titre" WHERE key_code="HEADING";
UPDATE intl set en="Headline", ru="Заголовок", fr="Manchette" WHERE key_code="HEADLINE";
UPDATE intl set en="Auto-adjusted height", ru="Автоматическая высота", fr="Hauteur auto-ajustée" WHERE key_code="HEIGHT_AUTO";
UPDATE intl set en="Hide on mobiles", ru="Скрытый в телефоне", fr="Cacher sur les mobiles" WHERE key_code="HIDEONMOBILE";
UPDATE intl set en="Hide over", ru="Спрятать над", fr="Cacher au-delà" WHERE key_code="HIDEOVER";
UPDATE intl set en="Hide under", ru="Спрятать под", fr="Cacher en-deça" WHERE key_code="HIDEUNDER";
UPDATE intl set en="History", ru="История", fr="Historique" WHERE key_code="HISTORY";
UPDATE intl set en="Home", ru="Дом", fr="Accueil" WHERE key_code="HOME";
UPDATE intl set en="Home page", ru="Главная страница", fr="Page d'accueil" WHERE key_code="HOMEPAGE";
UPDATE intl set en="Homepage hash tag", ru="Тег главной страницы", fr="Hash tag de la page accueil" WHERE key_code="HOMETAG";
UPDATE intl set en="Home phone", ru="Домашний телефон", fr="Téléphone domicile" WHERE key_code="HOME_PHONE";
UPDATE intl set en="Horizontal", ru="Горизонтальный", fr="Horizontal" WHERE key_code="HORIZONTAL";
UPDATE intl set en="Hover bottom navigation", ru="Нижняя панель навигации", fr="Survol navigation bas" WHERE key_code="HOVERBOTTOMNAV";
UPDATE intl set en="Previous/Next Hover", ru="Предыдущее/Следующее наведение", fr="Survol de Suivant/Précédent" WHERE key_code="HOVERPREVNEXT";
UPDATE intl set en="How does this work?", ru="Как это работает?", fr="Comment ça marche?" WHERE key_code="HOW_TO";
UPDATE intl set en="Hubs administrator", ru="Администратор хабов", fr="Administrateur de hubs" WHERE key_code="HUBS_ADMIN";
UPDATE intl set en="Hub administrator", ru="Администратор хаба", fr="Administrateur du hub" WHERE key_code="HUB_ADMIN";
UPDATE intl set en="Hub type", ru="Тип хаба", fr="Type de hub" WHERE key_code="HUB_TYPE";
UPDATE intl set en="Ident", ru="ID", fr="Identifiant" WHERE key_code="IDENT";
UPDATE intl set en="Iframe", ru="Iframe", fr="Iframe" WHERE key_code="IFRAME";
UPDATE intl set en="We are sorry, your navigator doesn't support the required features (iframe)", ru="Извините, ваш браузер не поддерживает требуемые параметры (iframe)", fr="Nous sommes désolés, votre navigateur ne supporte pas les fonctionnalités requises (iframe)" WHERE key_code="IFRAME_NOT_SUPPORTED";
UPDATE intl set en="Image", ru="Картинка", fr="Image" WHERE key_code="IMAGE";
UPDATE intl set en="Slideshow", ru="Слайдшоу", fr="Diaporama" WHERE key_code="IMAGE_PLAYER";
UPDATE intl set en="Image as background", ru="Использовать картинку как фон", fr="Image en fond" WHERE key_code="IMG_AS_BG";
UPDATE intl set en="Gallery", ru="Галерея", fr="Galerie" WHERE key_code="IMG_GALLERY";
UPDATE intl set en="Import photos", ru="Импорт фотографий", fr="Importer des photos" WHERE key_code="IMPORT_PHOTOS";
UPDATE intl set en="Out", ru="Вход", fr="Entrée" WHERE key_code="IN";
UPDATE intl set en="Please, input the new name", ru="Пожалуйста, введите новое время", fr="Veuillez, saisissez le nouveau nom" WHERE key_code="INPUT_NEW_NAME";
UPDATE intl set en="Insert", ru="Вставить", fr="Insérer" WHERE key_code="INSERT";
UPDATE intl set en="Inseert an hyper-link", ru="Вставить гипер-ссылку", fr="Insérer un hyper-lien" WHERE key_code="INSERT_LINK";
UPDATE intl set en="Sorry, an internal error has occurred !!!", ru="Произошла внутренняя ошибка!", fr="Désolé, une erreur interne s'est produite !!!" WHERE key_code="INTERNAL_ERROR";
UPDATE intl set en="Invite a contact", ru="Пригласить друга", fr="Inviter un contact" WHERE key_code="INVITE_CONTACT";
UPDATE intl set en="Work in progress", ru="В процессе", fr="En cours de réalisation" WHERE key_code="IN_PROGRESS";
UPDATE intl set en="<b><u>{0}</u></b> is available", ru="<b><u>{0}</u></b> доступен", fr="<b><u>{0}</u></b> est disponible" WHERE key_code="IS_AVAILABLE";
UPDATE intl set en="Is required", ru="требуется ", fr="Est requis" WHERE key_code="IS_REQUIRED";
UPDATE intl set en="<b><u>{0}</u></b> is unavailable", ru="<b><u>{0}</u></b> недоступен", fr="<b><u>{0}</u></b> est indisponible" WHERE key_code="IS_UNAVAILABLE";
UPDATE intl set en="Italic", ru="Курсив", fr="Italic" WHERE key_code="ITALIC";
UPDATE intl set en="Justify", ru="Выровнять", fr="Justifié" WHERE key_code="JUSTIFY";
UPDATE intl set en="Alignment", ru="Выравнивание", fr="Alignement" WHERE key_code="JUSTIFY-CONTENT";
UPDATE intl set en="Keyboard navigation", ru="Управление клавиатурой", fr="Navigation par clavier" WHERE key_code="KEYBNAV";
UPDATE intl set en="Keywords", ru="Ключевые слова", fr="Mots clefs" WHERE key_code="KEYWORDS";
UPDATE intl set en="Kb", ru="Кб", fr="Ko" WHERE key_code="KILO_BYTE";
UPDATE intl set en="Label", ru="Метка", fr="Label" WHERE key_code="LABEL";
UPDATE intl set en="Landscape", ru="Макет", fr="Paysage" WHERE key_code="LANDSCAPE";
UPDATE intl set en="Lastname", ru="Фамилия", fr="Nom" WHERE key_code="LASTNAME";
UPDATE intl set en="Layer", ru="Слой", fr="Calque" WHERE key_code="LAYER";
UPDATE intl set en="Layer container", ru="Контейнер слоя", fr="Conteneur de calque" WHERE key_code="LAYERSCONTAINER";
UPDATE intl set en="Layouts", ru="Макеты", fr="Layouts" WHERE key_code="LAYOUTS";
UPDATE intl set en="Changes on current layout will be lost. Are you sure to load a new one?", ru="Изменения на этом макете не сохранятся. Вы уверены, что хотите загрузить новый макет?", fr="Les modifications sur le canavas actuel seront perdues. charger tout de même un nouveau canevas?" WHERE key_code="LAYOUT_ALREADY_LOADED";
UPDATE intl set en="This element is imported from {0}. Change are possible only at the source.", ru="Этот объект импортирован из {0}. Измения возможны только в источнике.", fr="Cet élément est importé depuis le layout {0}. Il ne peut être modifié qu'à la source." WHERE key_code="LAYOUT_IMPORTED";
UPDATE intl set en="Layout not found", ru="Макет не найден", fr="Layout introuvable" WHERE key_code="LAYOUT_NOT_FOUND";
UPDATE intl set en="Team leader", ru="Лидер команды", fr="Animateur" WHERE key_code="LEADER";
UPDATE intl set en="Learn more", ru="Узнать больше", fr="En savoir plus" WHERE key_code="LEARN_MORE";
UPDATE intl set en="Leave", ru="Покинуть", fr="Quitter" WHERE key_code="LEAVE";
UPDATE intl set en="Left", ru="Слева", fr="Gauche" WHERE key_code="LEFT";
UPDATE intl set en="Let's see!", ru="Давайте посмотрим!", fr="Let's see!" WHERE key_code="LETS_SEE";
UPDATE intl set en="Library", ru="Библиотека", fr="Bibliothèque" WHERE key_code="LIBRARY";
UPDATE intl set en="Line", ru="Строка", fr="Ligne" WHERE key_code="LINE";
UPDATE intl set en="Link", ru="Ссылка", fr="Lien" WHERE key_code="LINK";
UPDATE intl set en="Links", ru="Ссылки", fr="Liens" WHERE key_code="LINKS";
UPDATE intl set en="The link is not working properly", ru="Ссылка работает неверно", fr="Ce lien ne semble pas fonctionner correctement" WHERE key_code="LINK_NOT_WORKING";
UPDATE intl set en="List", ru="Список", fr="Lister" WHERE key_code="LIST";
UPDATE intl set en="Lock", ru="Заблокировать", fr="Verrouiller" WHERE key_code="LOCK";
UPDATE intl set en="Login", ru="Войти", fr="Connexion" WHERE key_code="LOGIN";
UPDATE intl set en="Connection failed", ru="Соединение прервано", fr="Connexion échouée" WHERE key_code="LOGIN_FAILED";
UPDATE intl set en="Please, login to have access to this site content", ru="Пожалуйста, войдите на сайт, чтобы пользоваться им", fr="Veuillez vous connecter pour accéder au contenu de ce site" WHERE key_code="LOGIN_REQUIRED";
UPDATE intl set en="Logout", ru="Выйти", fr="Déconnecter" WHERE key_code="LOGOUT";
UPDATE intl set en="Loop play", ru="Проиграть цикл", fr="Lecture en boucle" WHERE key_code="LOOPS";
UPDATE intl set en="Enter here below you e-mail address or your username (id).<br/>a reset link will be sent to your e-mail address.", ru="Введите свой e-mail или логин (id).<br/> Ссылка для сброса будет отправлена на ваш e-mail адрес.", fr="Entrez ci-dessous votre adresse e-mail ou votre identfiant.<br/>un lien de réinitialisation sera envoyé à votre adresse e-mail." WHERE key_code="LOST_PASSWORD";
UPDATE intl set en="Male", ru="Муж", fr="Homme" WHERE key_code="MALE";
UPDATE intl set en="Manage", ru="Управление", fr="Gérer" WHERE key_code="MANAGE";
UPDATE intl set en="Managed hubs", ru="Управление хабами", fr="Hubs gérés" WHERE key_code="MANAGED_HUBS";
UPDATE intl set en="Map", ru="Карта", fr="Carte" WHERE key_code="MAP";
UPDATE intl set en="Margin", ru="Поле ", fr="Marge" WHERE key_code="MARGIN";
UPDATE intl set en="Outside margins", ru="Наружные поля", fr="Marges extérieures" WHERE key_code="MARGINS";
UPDATE intl set en="Side margins", ru="Боковые поля", fr="Marges latérales" WHERE key_code="MARGINS_H";
UPDATE intl set en="Vertical margins", ru="Вертикальные поля", fr="Marges verticales" WHERE key_code="MARGINS_V";
UPDATE intl set en="Bottom margin", ru="Нижнее поле", fr="Marge en bas" WHERE key_code="MARGIN_BOTTOM";
UPDATE intl set en="Left margin", ru="Левое поле", fr="Marge à gauche" WHERE key_code="MARGIN_LEFT";
UPDATE intl set en="Right margin", ru="Правое поле", fr="Marge à droite" WHERE key_code="MARGIN_RIGHT";
UPDATE intl set en="Text margin", ru="Текстовое поле", fr="Marge text" WHERE key_code="MARGIN_TEXT";
UPDATE intl set en="Top margin", ru="Верхнее поле", fr="Marge en haut" WHERE key_code="MARGIN_TOP";
UPDATE intl set en="Sorry, uplaod file size is limited at", ru="Извините, размер загружаемого файла не может превышать", fr="Désolé, la taille des fichiers en dépôt est limitée à" WHERE key_code="MAX_UPLOAD_LIMIT";
UPDATE intl set en="Maybe", ru="Может быть", fr="Peut-être" WHERE key_code="MAYBE";
UPDATE intl set en="Media", ru="Медиа", fr="Media" WHERE key_code="MEDIA";
UPDATE intl set en="Media library", ru="Библиотека медиа", fr="Médiathèque" WHERE key_code="MEDIA_LIB";
UPDATE intl set en="Media library", ru="Библиотека медиа", fr="Médiathèque" WHERE key_code="MEDIA_LIBRARY";
UPDATE intl set en="Mb", ru="Мб", fr="Mo" WHERE key_code="MEGA_BYTE";
UPDATE intl set en="Members", ru="Участники", fr="Membres" WHERE key_code="MEMBERS";
UPDATE intl set en="Menu", ru="Меню", fr="Menu" WHERE key_code="MENU";
UPDATE intl set en="Message", ru="Сообщение", fr="Message" WHERE key_code="MESSAGE";
UPDATE intl set en="Middle", ru="Середина", fr="Milieu" WHERE key_code="MIDDLE";
UPDATE intl set en="Miscellaneous", ru="Другое", fr="Divers" WHERE key_code="MISC";
UPDATE intl set en="Missing arguments", ru="Отсутствие аргумента", fr="Arguments manquants" WHERE key_code="MISSING_ARGUMENTS";
UPDATE intl set en="Mb", ru="Мб", fr="Mo" WHERE key_code="MO";
UPDATE intl set en="Mobile phone", ru="Мобильный телефон", fr="Téléphone mobile" WHERE key_code="MOBILE_PHONE";
UPDATE intl set en="Mode", ru="Режим", fr="Mode" WHERE key_code="MODE";
UPDATE intl set en="Models", ru="Шаблоны", fr="Modeles" WHERE key_code="MODELS";
UPDATE intl set en="Moderator", ru="Модератор", fr="Modérateur" WHERE key_code="MODERATOR";
UPDATE intl set en="Module {0} has not been found", ru="Модуль {0} не найден.", fr="Impossible de trouver le module {0}" WHERE key_code="MODULE_NOT_FOUND";
UPDATE intl set en="Move", ru="Переместить", fr="Déplacer" WHERE key_code="MOVE";
UPDATE intl set en="My account", ru="Мой профиль", fr="Mon compte" WHERE key_code="MY_ACCOUNT";
UPDATE intl set en="My personal data", ru="Личные данные", fr="Mes données personnelles" WHERE key_code="MY_DATA";
UPDATE intl set en="My hubs", ru="Мои хабы", fr="Mes hubs" WHERE key_code="MY_HUBS";
UPDATE intl set en="My media library", ru="Моя медиабиблиотека ", fr="Ma médiathèque" WHERE key_code="MY_MEDIA";
UPDATE intl set en="My pages", ru="Мои страницы", fr="Mes pages" WHERE key_code="MY_PAGES";
UPDATE intl set en="My password", ru="Пароль", fr="Mon mot de passe" WHERE key_code="MY_PASSWORD";
UPDATE intl set en="My profile", ru="Мой профиль", fr="Mon profil" WHERE key_code="MY_PROFILE";
UPDATE intl set en="My rings", ru="Мой круг (окружение)", fr="Mes cercles" WHERE key_code="MY_RINGS";
UPDATE intl set en="My settings", ru="Настройки", fr="Mes paramètres" WHERE key_code="MY_SETTINGS";
UPDATE intl set en="My sites", ru="Мои сайты", fr="Mes sites" WHERE key_code="MY_SITES";
UPDATE intl set en="My personal space", ru="Личное пространство", fr="Mon espace personnel" WHERE key_code="MY_SPACE";
UPDATE intl set en="My Spaces", ru="Мо", fr="Mes Espaces" WHERE key_code="MY_SPACES";
UPDATE intl set en="My styles", ru="Мои стили", fr="Mes styles" WHERE key_code="MY_STYLES";
UPDATE intl set en="My tools", ru="Инструменты", fr="Mes outils" WHERE key_code="MY_TOOLS";
UPDATE intl set en="Name", ru="Имя", fr="Nom" WHERE key_code="NAME";
UPDATE intl set en="Navigation buttons", ru="Кнопки навигации", fr="Boutons de navigation" WHERE key_code="NAVBUTTONS";
UPDATE intl set en="Navigation", ru="Навигация по странице", fr="Navigation" WHERE key_code="NAVIGATION";
UPDATE intl set en="Previous/Next Buttons", ru="Кнопки Назад/Вперед", fr="Boutons Suivant/Précédent" WHERE key_code="NAVPREVNEXT";
UPDATE intl set en="Start/Stop buttons", ru="Кнопки Начать/Остановить", fr="Boutons Arrêt/Lecture" WHERE key_code="NAVSTARTSTOP";
UPDATE intl set en="New", ru="Новый", fr="Nouveau" WHERE key_code="NEW";
UPDATE intl set en="News", ru="Новости", fr="Actualités" WHERE key_code="NEWS";
UPDATE intl set en="Newsletter", ru="Рассылка", fr="Newsletter" WHERE key_code="NEWSLETTER";
UPDATE intl set en="News feed", ru="Новостная лента", fr="Flux d'actualités" WHERE key_code="NEWS_FEED";
UPDATE intl set en="New folder", ru="Новая папка", fr="Nouveau dossier" WHERE key_code="NEW_FOLDER";
UPDATE intl set en="New form", ru="Новая форма", fr="Nouveau formulaire" WHERE key_code="NEW_FORM";
UPDATE intl set en="New Layout", ru="Новый слой", fr="Nouveau layout" WHERE key_code="NEW_LAYOUT";
UPDATE intl set en="New menu", ru="Новое меню", fr="Nouveau menu" WHERE key_code="NEW_MENU";
UPDATE intl set en="New page", ru="Новая страница", fr="Nouvelle page" WHERE key_code="NEW_PAGE";
UPDATE intl set en="New site", ru="Новый сайт", fr="Nouveau site" WHERE key_code="NEW_SITE";
UPDATE intl set en="New slider", ru="Новый ползунок", fr="Nouvelle visionneuse" WHERE key_code="NEW_SLIDER";
UPDATE intl set en="New slideshow", ru="Новое слайдшоу", fr="Nouveau diaporama" WHERE key_code="NEW_SLIDESHOW";
UPDATE intl set en="New style", ru="Новый стиль", fr="Nouveau style" WHERE key_code="NEW_STYLE";
UPDATE intl set en="Add new user", ru="Добавить нового пользователя", fr="Créer un nouvel utilisateur" WHERE key_code="NEW_USER";
UPDATE intl set en="No", ru="Нет", fr="Non" WHERE key_code="NO";
UPDATE intl set en="<b><u>{0}</u></b> isn't available", ru="<b><u>{0}</u></b> недоступен", fr="<b><u>{0}</u></b> n'est pas disponible" WHERE key_code="NOT_AVAILABLE";
UPDATE intl set en="Not spam", ru="Не спам", fr="Pas du spam" WHERE key_code="NOT_SPAM";
UPDATE intl set en="Coming soon", ru="Скоро появится", fr="Bientôt disponible" WHERE key_code="NOT_YET_IMPLEMENTED";
UPDATE intl set en="No, cancel!", ru="Отмена", fr="Non, annuler" WHERE key_code="NO_CANCEL";
UPDATE intl set en="There is no community being selected for this operation!", ru="Для данного действия не выбрано сообщество.", fr="Il n'y a pas de communauté sélectionnée pour cette action !" WHERE key_code="NO_COMMUNITY";
UPDATE intl set en="Content not found", ru="Содержимое не найдено", fr="Aucun contenu trouvé" WHERE key_code="NO_CONTENT";
UPDATE intl set en="Directory sharing or copying is not (yet) available!", ru="Совместный доступ к файлам и копирование (пока) недоступно.", fr="Le partage ou la copie de répertoire n'est pas (encore) disponible" WHERE key_code="NO_DIR_SHARING";
UPDATE intl set en="Object with type %s could not be dropped on a container of type %s", ru="Объект такого типа  % не может быть здесь размещён. ", fr="L'objet de type %s ne peut être déposé dans un conteneur de type %s" WHERE key_code="NO_DROP";
UPDATE intl set en="Feed unvailable", ru="Информация недоступна.", fr="Feed indisponible" WHERE key_code="NO_FEED";
UPDATE intl set en="Hasn't yet customised his/her profile page", ru="Ещё не настроил(а) свою страницу.", fr=" n'a pas encore personnalisé sa page de profile" WHERE key_code="NO_HOME_PAGE";
UPDATE intl set en="The invitees list is empty!", ru="Лист приглашений пуст!", fr="La liste des invités est vide!" WHERE key_code="NO_INVITEE";
UPDATE intl set en="There is no message to send!", ru="Нет сообщений для отправки.", fr="Il n'y apas de message à envoyer!" WHERE key_code="NO_MESSAGE";
UPDATE intl set en="No recipient has been specified for this message", ru="Не указан адресат сообщения", fr="Il n'y a pas de destinataire désigné pour ce message" WHERE key_code="NO_RECIPIENT";
UPDATE intl set en="Unavailable tutorial", ru="Руководство недоступно", fr="Tutoriel indisponible" WHERE key_code="NO_TUTORIAL";
UPDATE intl set en="Object", ru="Объект", fr="Objet" WHERE key_code="OBJECT";
UPDATE intl set en="Obsoleted!", ru="Устаревший!", fr="Fonction obsolète!" WHERE key_code="OBSOLETED";
UPDATE intl set en="Office phone", ru="Рабочий телефон", fr="Téléphone travail" WHERE key_code="OFFICE_PHONE";
UPDATE intl set en="Offset x in", ru="Сместить по оси x вправо", fr="Offset x d'entrée" WHERE key_code="OFFSETXIN";
UPDATE intl set en="Offset x out", ru="Сместить по оси x влево", fr="Offset x de sortie" WHERE key_code="OFFSETXOUT";
UPDATE intl set en="Offset y in", ru="Сместить по оси y вверх", fr="Offset y d'entrée" WHERE key_code="OFFSETYIN";
UPDATE intl set en="Offset y out", ru="Сместить по оси y вниз", fr="Offset y de sortie" WHERE key_code="OFFSETYOUT";
UPDATE intl set en="Old", ru="Старый", fr="Ancien" WHERE key_code="OLD";
UPDATE intl set en="Old password", ru="Старый пароль", fr="Ancien mot de passe" WHERE key_code="OLD_PASSWORD";
UPDATE intl set en="Online", ru="Онлайн", fr="Connexions" WHERE key_code="ONLINE";
UPDATE intl set en="Only accept", ru="Принимаются только", fr="Accepte seulement" WHERE key_code="ONLY_ACCEPT";
UPDATE intl set en="Opacity", ru="Непрозрачность", fr="Transapence" WHERE key_code="OPACITY";
UPDATE intl set en="Open", ru="Открыть", fr="Ouvrir" WHERE key_code="OPEN";
UPDATE intl set en="Options", ru="Опции", fr="Options" WHERE key_code="OPTIONS";
UPDATE intl set en="Order", ru="Порядок", fr="Ordonner" WHERE key_code="ORDER";
UPDATE intl set en="Out", ru="Выход", fr="Sortie" WHERE key_code="OUT";
UPDATE intl set en="Reuse the name", ru="Использовать имя снова", fr="Réutiliser le nom" WHERE key_code="OVERRIDE";
UPDATE intl set en="Padding", ru="Отступ", fr="Padding" WHERE key_code="PADDING";
UPDATE intl set en="Inside margins", ru="Внутреннее поле", fr="Marges intérieures" WHERE key_code="PADDINGS";
UPDATE intl set en="Padding", ru="Отступ", fr="Padding" WHERE key_code="PADDING_ALL";
UPDATE intl set en="Padding bottom", ru="Отступ снизу", fr="Padding bas" WHERE key_code="PADDING_BOTTOM";
UPDATE intl set en="Padding left", ru="Отступ слева", fr="Padding gauche" WHERE key_code="PADDING_LEFT";
UPDATE intl set en="Padding right", ru="Отступ справа", fr="Padding droite" WHERE key_code="PADDING_RIGHT";
UPDATE intl set en="Padding top", ru="Отступ сверху", fr="Padding haut" WHERE key_code="PADDING_TOP";
UPDATE intl set en="Pages", ru="Страницы", fr="Pages" WHERE key_code="PAGES";
UPDATE intl set en="Couldn't find page {0}", ru="Невозможно найти страницу {0}", fr="La page {0} n'a pu être trouvée" WHERE key_code="PAGE_NOT_FOUND";
UPDATE intl set en="Paragraph", ru="Параграф", fr="Paragraphe" WHERE key_code="PARAGRAPH";
UPDATE intl set en="Password", ru="Пароль", fr="Mot de passe" WHERE key_code="PASSWORD";
UPDATE intl set en="Confirm password", ru="Подтвердить пароль", fr="Confirmation mot de passe" WHERE key_code="PASSWORD_CHECK";
UPDATE intl set en="Pause when over", ru="Приостановить, когда", fr="Pause au survol" WHERE key_code="PAUSEONHOVER";
UPDATE intl set en="Pause time", ru="Время паузы", fr="Temps de pause" WHERE key_code="PAUSETIME";
UPDATE intl set en="Pdf, text", ru="Pdf, текст", fr="Pdf, texte" WHERE key_code="PDF_TXT";
UPDATE intl set en="Sorry, this function is not yet operating", ru="Извините, данная функция пока недоступна. ", fr="Désolé, cette fonction n'est pas encore mise en service" WHERE key_code="PENDING_FUNCTION";
UPDATE intl set en="Percent", ru="Процентов", fr="Pourcentage" WHERE key_code="PERCENT";
UPDATE intl set en="Perspective", ru="Перспектива", fr="Perspective" WHERE key_code="PERSPECTIVE";
UPDATE intl set en="Perspective in", ru="Перспектива в", fr="Perspective d'entrée" WHERE key_code="PERSPECTIVEIN";
UPDATE intl set en="", ru="Перспектива из", fr="Perspective de sortie" WHERE key_code="PERSPECTIVEOUT		";
UPDATE intl set en="Phone number", ru="Номер телефона", fr="Numéro de téléléphone" WHERE key_code="PHONE_NUMBER";
UPDATE intl set en="Photo", ru="Фото", fr="Photo" WHERE key_code="PHOTO";
UPDATE intl set en="Pictures", ru="Фотографии", fr="Photos" WHERE key_code="PHOTOS";
UPDATE intl set en="Photo crop", ru="Обрезка фотографий", fr="Recadrage photo" WHERE key_code="PHOTO_CROP";
UPDATE intl set en="Photo editor", ru="Редактор фотографий", fr="Editeur de photo" WHERE key_code="PHOTO_EDITOR";
UPDATE intl set en="Private photo", ru="Личная фотография", fr="Photo privée" WHERE key_code="PHOTO_PRV";
UPDATE intl set en="Public photo", ru="Общедоступная фотография", fr="Photo publique" WHERE key_code="PHOTO_PUB";
UPDATE intl set en="Restricted photo", ru="Фотография с ограниченным использованием", fr="Photo restreint" WHERE key_code="PHOTO_RES";
UPDATE intl set en="Pick a color", ru="Выбрать цвет", fr="Selectionnez une couleur" WHERE key_code="PICK_COLOR";
UPDATE intl set en="Pictogram", ru="Символ", fr="Pictogramme" WHERE key_code="PICTO";
UPDATE intl set en="Pie", ru="Круговая диаграмма", fr="Camembert" WHERE key_code="PIE";
UPDATE intl set en="Pixel", ru="Пиксель", fr="Pixel" WHERE key_code="PIXEL";
UPDATE intl set en="Player", ru="Проигрыватель", fr="Lecteur" WHERE key_code="PLAYER";
UPDATE intl set en="Please, confirm", ru="Пожалуйста, подтвердите", fr="Veuillez confirmer" WHERE key_code="PLEASE_CONFIRM";
UPDATE intl set en="Please, sign in first !", ru="Пожалуйста, войдите в свой профиль", fr="Veuillez d'abord vous connecter !" WHERE key_code="PLEASE_CONNECT";
UPDATE intl set en="Popup", ru="Всплывающее окно", fr="Popup" WHERE key_code="POPUP";
UPDATE intl set en="Portrait", ru="Портрет", fr="Portrait" WHERE key_code="PORTRAIT";
UPDATE intl set en="Positioning", ru="Позиция", fr="Positionnement" WHERE key_code="POSITIONING";
UPDATE intl set en="Postal address", ru="Почтовый адрес", fr="Adresse postale" WHERE key_code="POSTAL_ADDRESS";
UPDATE intl set en="Preferences", ru="Предпочтения", fr="Préférences" WHERE key_code="PREFERENCES";
UPDATE intl set en="Prepend to", ru="Добавить к", fr="Prepend à" WHERE key_code="PREPENDTO";
UPDATE intl set en="Preregister", ru="Зарегистрировать предварительно", fr="Pré-inscription" WHERE key_code="PREREGISTER";
UPDATE intl set en="Preset block", ru="Заданный блок", fr="Block tout fait" WHERE key_code="PRESET_BLOCK";
UPDATE intl set en="Preset shape", ru="Заданная форма", fr="Forme prédéfinies" WHERE key_code="PRESET_SHAPE";
UPDATE intl set en="to pre register", ru="Предварительная регистрация", fr="pour vous pré-enregistrez" WHERE key_code="PRESIGNON_MSG";
UPDATE intl set en="Enter your e-mail address to preregister", ru="Введите свой e-mail для предварительной регистрации.", fr="Entrez votre adresse e-mail pour vous pré-inscrire" WHERE key_code="PRESIGNON_PROMPT";
UPDATE intl set en="An e-mail will be sent for confirmation", ru="На ваш e-mail отправлено письмо для подтверждения.", fr="Un e-mail sera envoyé pour confirmation" WHERE key_code="PRESIGNON_TIP";
UPDATE intl set en="Preview", ru="Предпросмотр", fr="Aperçu" WHERE key_code="PREVIEW";
UPDATE intl set en="Thanks so much for your interest! please, fill in the fomr below, and will keep you updated upon drumee's readiness.", ru="Спасибо за проявленный интерес! Пожалуйста, заполните форму ниже, и мы будем держать вас в курсе об обновлениях Drumee.", fr="Merci pour votre intérêt !<br />veuillez renseigner le formulaire ci-dessous. Nous vous informerons dès la mise en service opérationnelle." WHERE key_code="PRE_SUBSCRIBE_MSG";
UPDATE intl set en="Private", ru="Частный", fr="Privé(e)" WHERE key_code="PRIVATE";
UPDATE intl set en="Private rings", ru="Приватный круг общения", fr="Cercles privés" WHERE key_code="PRIVATE_RINGS";
UPDATE intl set en="Private sites", ru="Частные сайты", fr="Sites privés" WHERE key_code="PRIVATE_SITES";
UPDATE intl set en="Private space", ru="Личное пространство", fr="Espace privée" WHERE key_code="PRIVATE_SPACE";
UPDATE intl set en="Privates Spaces", ru="Личное пространство", fr="Espaces Privés" WHERE key_code="PRIVATE_SPACES";
UPDATE intl set en="Privilege", ru="Права на управление", fr="Privilège" WHERE key_code="PRIVILEGE";
UPDATE intl set en="Profile", ru="Профиль", fr="Profil" WHERE key_code="PROFILE";
UPDATE intl set en="Profile page", ru="Страница профиля", fr="Page de profil" WHERE key_code="PROFILE_PAGE";
UPDATE intl set en="Profile photo", ru="Фото профиля", fr="Photo de profil" WHERE key_code="PROFILE_PHOTO";
UPDATE intl set en="Projects spaces", ru="Проекты", fr="Espaces projets" WHERE key_code="PROJECTS_SPACES";
UPDATE intl set en="Please, fill the form below", ru="Пожалуйста, заполните форму ниже.", fr="Veuillez remplir les champs ci-dessous" WHERE key_code="PROMPT_FORM";
UPDATE intl set en="Please, enter your message here.", ru="Пожалуйста, введите свое сообщение здесь.", fr="Merci de taper votre message ici." WHERE key_code="PROMPT_MSG";
UPDATE intl set en="Properties", ru="Свойства", fr="Proriétés" WHERE key_code="PROPERTIES";
UPDATE intl set en="Public accÃ¨s", ru="Публичный доступ", fr="Accès public" WHERE key_code="PUBLIC_ACCESS";
UPDATE intl set en="Public rings", ru="Общедоступный круг общения", fr="Cercles publics" WHERE key_code="PUBLIC_RINGS";
UPDATE intl set en="Public sites", ru="Публичные сайты", fr="Sites publics" WHERE key_code="PUBLIC_SITES";
UPDATE intl set en="Public hubs", ru="Публичные хабы", fr="Hubs publics" WHERE key_code="PUBLIC_SPACE";
UPDATE intl set en="Public Spaces", ru="Публичное пространство", fr="Espaces Publics" WHERE key_code="PUBLIC_SPACES";
UPDATE intl set en="Purge", ru="Очистить", fr="Purger" WHERE key_code="PURGE";
UPDATE intl set en="Question & answer", ru="Вопросы и ответы", fr="Question & réponse" WHERE key_code="QnA";
UPDATE intl set en="Random slideshow", ru="Случайный порядок", fr="Lecture aléatoire" WHERE key_code="RANDOMSLIDESHOW";
UPDATE intl set en="This box cannot be directly suppressed.", ru="Этот блок нельзя скрыть напрямую.", fr="Cette boîte ne peut pas être supprimée directement." WHERE key_code="READONLY_BOX";
UPDATE intl set en="Redo", ru="Повторить", fr="Refaire" WHERE key_code="REDO";
UPDATE intl set en="Redraw", ru="Изменить", fr="Redessiner" WHERE key_code="REDRAW";
UPDATE intl set en="Refresh", ru="Обновить", fr="Actualiser" WHERE key_code="REFRESH";
UPDATE intl set en="Registered", ru="Зарегистрировано", fr="Inscrits" WHERE key_code="REGISTERED";
UPDATE intl set en="Please, fill in form herebelow, an activation link will be sent to the specified e-mail adress", ru="Пожалуйста, заполните форму ниже. Ссылка активации будет отправлена на указанный e-mail адрес.", fr="Remplissez le formulaire ci-dessous. Un lien d'activation sera envoyé à l'adresse e-mail que vous aurez indiquée." WHERE key_code="REGISTER_WELCOME";
UPDATE intl set en="Remove", ru="Удалить", fr="Supprimer" WHERE key_code="REMOVE";
UPDATE intl set en="Rename", ru="Переименовать", fr="Renommer" WHERE key_code="RENAME";
UPDATE intl set en="Replace", ru="Переместить", fr="Remplacer" WHERE key_code="REPLACE";
UPDATE intl set en="Reposition the picture", ru="Перемещение фотографии", fr="Repositionner la photo" WHERE key_code="REPOSITION_PHOTO";
UPDATE intl set en="This field must be a date (dd/mm/yyyy)", ru="В этом поле должна быть дата (дд/мм/гггг)", fr="Ce champ doit être une date (jj/mm/aaaa)" WHERE key_code="REQUIRE_DATE";
UPDATE intl set en="Must be a valid DNS name", ru="Должно быть действительное DNS имя. ", fr="Doit être un nom DNS valide" WHERE key_code="REQUIRE_DNS_NAME";
UPDATE intl set en="A valid e-mail address is required", ru="Требуется действительный e-mail адрес.", fr="Une adresse e-mail valide est requise" WHERE key_code="REQUIRE_EMAIL";
UPDATE intl set en="A valid e-mail address or an ident is required", ru="Требуется действительный e-mail адрес или логин.", fr="Une adresse e-mail valide ou un identidiant est requis" WHERE key_code="REQUIRE_EMAIL_OR_ID";
UPDATE intl set en="This field requires a ident", ru="В этом поле нужно ввести логин.", fr="Ce champ requiert un identifiant" WHERE key_code="REQUIRE_FIELD_IDENT";
UPDATE intl set en="Contains only letters, digits and ._- Must not begin with --", ru="Содержит только буквы, цифры и  ._-. Не может начинаться с -", fr="Comporte seulement chiffres, lettres et les caractères ._- Ne doit pas commencer par --" WHERE key_code="REQUIRE_HASHTAG";
UPDATE intl set en="Only accepts letters, gidits and -_.", ru="Принимает только буквы, цифры и  ._-. ", fr="Accepte seulement lettres, chiffres et -_." WHERE key_code="REQUIRE_ID";
UPDATE intl set en="This field must be a number", ru="В этом поле нужно ввести число.", fr="Ce champ doit être un nombre" WHERE key_code="REQUIRE_NUMBER";
UPDATE intl set en="Must contain only digits, spaces or dots", ru="Может содержать только цифры, пробелы и точки. ", fr="Doit comporter uniquement des chiffres, espaces ou  points" WHERE key_code="REQUIRE_PHONE";
UPDATE intl set en="A text line is required", ru="Требуется текстовая строка", fr="Une ligne de texte est requise" WHERE key_code="REQUIRE_STRING";
UPDATE intl set en="Text is required", ru="Требуется ввести текст.", fr="Du texte est requis" WHERE key_code="REQUIRE_TEXT";
UPDATE intl set en="the field {0} is required", ru="В поле {0} требуемый формат", fr="le champ {0} est requis" WHERE key_code="REQUIRE_THAT_FIELD";
UPDATE intl set en="This field is required.", ru="Требуется поле.", fr="Ce champ  est requis." WHERE key_code="REQUIRE_THIS_FIELD";
UPDATE intl set en="This action is effective for only authorized persons.", ru="Эта функция доступна только для авторизированных пользователей.", fr="Cette action est effective seulement pour les personnes autorisées." WHERE key_code="RESERVED_ACTION";
UPDATE intl set en="Reset", ru="Сбросить", fr="Réinitialiser" WHERE key_code="RESET";
UPDATE intl set en="Reset password", ru="Сбросить пароль", fr="Réinitialiser le mot de passe" WHERE key_code="RESET_PASSWORD";
UPDATE intl set en="Responsive", ru="Адаптирующийся", fr="Responsive" WHERE key_code="RESPONSIVE";
UPDATE intl set en="Responsive under", ru="Адаптирующийся под", fr="Responsive en-dessous de" WHERE key_code="RESPONSIVEUNDER";
UPDATE intl set en="Restricted rings", ru="Ограниченный круг", fr="Cercles restreints" WHERE key_code="RESTRICTED_RINGS";
UPDATE intl set en="Restricted sites", ru="Ограниченный сайт", fr="Sites restreints" WHERE key_code="RESTRICTED_SITES";
UPDATE intl set en="Transverse space", ru="Сечение", fr="Espace transversal" WHERE key_code="RESTRICTED_SPACE";
UPDATE intl set en="Transverse Spaces", ru="Сечение", fr="Espaces Transversaux" WHERE key_code="RESTRICTED_SPACES";
UPDATE intl set en="Retouch", ru="Ретушь", fr="Retoucher" WHERE key_code="RETOUCH";
UPDATE intl set en="Retrieve", ru="Восстановить", fr="Récupérer" WHERE key_code="RETRIEVE";
UPDATE intl set en="Reuse style", ru="Повторно использовать стиль", fr="Reproduire le style" WHERE key_code="REUSE_STYLE";
UPDATE intl set en="Rich text", ru="Форматированный текст", fr="Texte enrichi" WHERE key_code="RICH_TEXT";
UPDATE intl set en="Right", ru="Справа", fr="Droite" WHERE key_code="RIGHT";
UPDATE intl set en="System administrator", ru="Системный администратор", fr="Administrateur système" WHERE key_code="ROOT";
UPDATE intl set en="Rotate", ru="Повернуть", fr="Rotation" WHERE key_code="ROTATE";
UPDATE intl set en="Rotation in", ru="Повернуть при входе", fr="Rotation d'entrée" WHERE key_code="ROTATEIN";
UPDATE intl set en="Rotate out", ru="Повернуть при выходе", fr="Rotation de sortie" WHERE key_code="ROTATEOUT";
UPDATE intl set en="Rotation x in", ru="Поворот по оси X при входе", fr="Rotation x d'entrée" WHERE key_code="ROTATEXIN";
UPDATE intl set en="Rotate x out", ru="Поворот по оси X при выходе", fr="Rotation x de sortie" WHERE key_code="ROTATEXOUT";
UPDATE intl set en="Rotation y in", ru="Поворот по оси Y при входе", fr="Rotation y d'entrée" WHERE key_code="ROTATEYIN";
UPDATE intl set en="Rotate y out", ru="Поворот по оси Y при выходе", fr="Rotation y de sortie" WHERE key_code="ROTATEYOUT";
UPDATE intl set en="Rotate left", ru="Повернуть влево", fr="Rotation à gauche" WHERE key_code="ROTATE_LEFT";
UPDATE intl set en="Rotate right", ru="Повернуть вправо", fr="Rotation à droite" WHERE key_code="ROTATE_RIGHT";
UPDATE intl set en="Rotation", ru="Поворот", fr="Rotation" WHERE key_code="ROTATION";
UPDATE intl set en="Horizontal rotation", ru="Горизонтальный поворот", fr="Rotation horizontale" WHERE key_code="ROTATIONX";
UPDATE intl set en="Vertical rotation", ru="Вертикальный поворот", fr="Rotation verticale" WHERE key_code="ROTATIONY";
UPDATE intl set en="Horizontal rotation", ru="Горизонтальный поворот", fr="Rotation horizontale" WHERE key_code="ROTATION_X";
UPDATE intl set en="Vertical rotation", ru="Вертикальный поворот", fr="Rotation verticale" WHERE key_code="ROTATION_Y";
UPDATE intl set en="RSS feed", ru="Лента новостей", fr="Fil RSS" WHERE key_code="RSS_FEED";
UPDATE intl set en="Saturation", ru="Насыщенность", fr="Saturation" WHERE key_code="SATURATION";
UPDATE intl set en="Save", ru="Сохранить", fr="Enregistrer" WHERE key_code="SAVE";
UPDATE intl set en="Save as...", ru="Сокранить как…", fr="Enregistrer sous..." WHERE key_code="SAVE_AS";
UPDATE intl set en="Please, save first your layout", ru="Пожалуйста, сначала сохраните ваш слой", fr="Veuillez d'abord enregister votre canevas." WHERE key_code="SAVE_LAYOUT_FIRST";
UPDATE intl set en="Zoom", ru="Масштабировать", fr="Zoom" WHERE key_code="SCALE";
UPDATE intl set en="Scale in", ru="Масштабировать при входе", fr="Echelle d'entrée" WHERE key_code="SCALEIN";
UPDATE intl set en="Scale out", ru="Масштабировать при выходе", fr="Echelle de sortie" WHERE key_code="SCALEOUT";
UPDATE intl set en="Scale x in", ru="Масштабировать по оси X при входе", fr="Echelle x d'entrée" WHERE key_code="SCALEXIN";
UPDATE intl set en="Scale x out", ru="Масштабировать по оси X при выходе", fr="Echelle x de sortie" WHERE key_code="SCALEXOUT";
UPDATE intl set en="Scale y in", ru="Масштабировать по оси Y при входе", fr="Echelle y d'entrée" WHERE key_code="SCALEYIN";
UPDATE intl set en="Scale y out", ru="Масштабировать по оси Y при выходе", fr="Echelle y de sortie" WHERE key_code="SCALEYOUT";
UPDATE intl set en="Scope", ru="Масштаб", fr="Diffusion" WHERE key_code="SCOPE";
UPDATE intl set en="Screen", ru="Экран", fr="Ecran" WHERE key_code="SCREEN";
UPDATE intl set en="Screen name", ru="Имя экрана", fr="Nom d'écran" WHERE key_code="SCREEN_NAME";
UPDATE intl set en="Search", ru="Поиск", fr="Chercher" WHERE key_code="SEARCH";
UPDATE intl set en="Security", ru="Безопасность", fr="Sécurité" WHERE key_code="SECURITY";
UPDATE intl set en="Your session has expired.", ru="Время сеанса истекло.", fr="Votre session a expiré." WHERE key_code="SESSION_EXPIRED";
UPDATE intl set en="Settings", ru="Настройки", fr="Paramètres" WHERE key_code="SETTINGS";
UPDATE intl set en="Set as homepage", ru="Установить как домашнюю страницу", fr="Mettre en page d'accueil" WHERE key_code="SET_AS_HOMEPAGE";
UPDATE intl set en="Set as profile photo", ru="Установить как фото профиля", fr="Photo de profil" WHERE key_code="SET_AS_PROFILE";
UPDATE intl set en="Shape", ru="Форма ", fr="Forme" WHERE key_code="SHAPE";
UPDATE intl set en="Share", ru="Поделиться", fr="Partager" WHERE key_code="SHARE";
UPDATE intl set en="Show bar timer", ru="Показать линейное время", fr="Afficher le chrono en barre" WHERE key_code="SHOWBARTIMER";
UPDATE intl set en="Show circle timer", ru="Показать круговое время", fr="Afficher le chrono en cercle" WHERE key_code="SHOWCIRCLETIMER";
UPDATE intl set en="Show until", ru="Показать до", fr="Afficher jusqu'à" WHERE key_code="SHOWUNTIL";
UPDATE intl set en="Show hub members", ru="Показать учатников хаба", fr="Afficher les membres" WHERE key_code="SHOW_HUBERS";
UPDATE intl set en="Show mates", ru="Показать друзей", fr="Afficher collaborateurs" WHERE key_code="SHOW_MATES";
UPDATE intl set en="Sign in", ru="Зарегистрироваться", fr="Inscript." WHERE key_code="SIGN_IN";
UPDATE intl set en="Simple text", ru="Простой текст", fr="Texte simple" WHERE key_code="SIMPLE_TEXT";
UPDATE intl set en="Site", ru="Сайт", fr="Site" WHERE key_code="SITE";
UPDATE intl set en="Site ident", ru="ID сайта", fr="Identifiant du site" WHERE key_code="SITE_IDENT";
UPDATE intl set en="Site manager", ru="Управление сайтом", fr="Gestionnaire du site" WHERE key_code="SITE_MANAGER";
UPDATE intl set en="Site name", ru="Имя сайта", fr="Nom du site" WHERE key_code="SITE_NAME";
UPDATE intl set en="The site %s doesn't exist", ru="Сайт %s не существует", fr="Le site %s n'existe pas" WHERE key_code="SITE_NOT_FOUND";
UPDATE intl set en="Site pages", ru="Страницы сайта", fr="Pages du site" WHERE key_code="SITE_PAGES";
UPDATE intl set en="Sizes rule", ru="Правила размеров", fr="Règle des tailles" WHERE key_code="SIZES_RULE";
UPDATE intl set en="Horizontal skew", ru="Горизонтальный наклон", fr="Vrille horizontale" WHERE key_code="SKEWX";
UPDATE intl set en="Skew x in", ru="Наклон по оси X при входе", fr="Vrille x d'entrée" WHERE key_code="SKEWXIN";
UPDATE intl set en="Skew x out", ru="Наклон по оси X при выходе", fr="Vrille x de sortie" WHERE key_code="SKEWXOUT";
UPDATE intl set en="Vertical skew", ru="Вертикальный наклон", fr="Vrille verticale" WHERE key_code="SKEWY";
UPDATE intl set en="Skew y in", ru="Наклон по оси Y при входе", fr="Vrille y d'entrée" WHERE key_code="SKEWYIN";
UPDATE intl set en="Skew y out", ru="Наклон по оси Y при выходе", fr="Vrille y de sortie" WHERE key_code="SKEWYOUT";
UPDATE intl set en="Skin", ru="Обложка", fr="Habillage" WHERE key_code="SKIN";
UPDATE intl set en="Slide", ru="Слайд", fr="Planche" WHERE key_code="SLIDE";
UPDATE intl set en="Duration while slides are being displayed", ru="Время показа слайдов", fr="Durée d'affichage des planches" WHERE key_code="SLIDEDELAY";
UPDATE intl set en="Slider", ru="Ползунок", fr="Diaporama" WHERE key_code="SLIDER";
UPDATE intl set en="Slider fade duration", ru="Скорость исчезновения слайда", fr="Durée de fondu" WHERE key_code="SLIDERFADEINDURATION";
UPDATE intl set en="Slides", ru="Ползунки", fr="Planches diapo" WHERE key_code="SLIDES";
UPDATE intl set en="Slideshow", ru="Слайдшоу", fr="Diaporama" WHERE key_code="SLIDESHOW";
UPDATE intl set en="Slide to bottom", ru="Прокрутить вниз", fr="Défilement vers le bas" WHERE key_code="SLIDE_TO_BOTTOM";
UPDATE intl set en="Slide to left", ru="Прокрутить влево", fr="Défilement vers la gauche" WHERE key_code="SLIDE_TO_LEFT";
UPDATE intl set en="Slide to right", ru="Прокрутить вправо", fr="Défilement vers la droite" WHERE key_code="SLIDE_TO_RIGHT";
UPDATE intl set en="Slide to top", ru="Прокрутить вверх", fr="Défilement vers le haut" WHERE key_code="SLIDE_TO_TOP";
UPDATE intl set en="Smart phone", ru="Смартфон", fr="Smart phone" WHERE key_code="SMART_PHONE";
UPDATE intl set en="Social network", ru="Социальная сеть", fr="Réseau social" WHERE key_code="SOCIAL_NETWORK";
UPDATE intl set en="Soc. Net", ru="Соцсеть", fr="Rsx Soc." WHERE key_code="SOC_NET";
UPDATE intl set en="Source", ru="Источник", fr="Source" WHERE key_code="SOURCE";
UPDATE intl set en="Spaces", ru="Пространства", fr="Espaces" WHERE key_code="SPACES";
UPDATE intl set en="Spaces administrator", ru="Администратор пространства", fr="Administrateur d'espaces" WHERE key_code="SPACES_ADMIN";
UPDATE intl set en="Space around", ru="Пространство вокруг", fr="Espace autour" WHERE key_code="SPACE_AROUND";
UPDATE intl set en="Space available", ru="Доступное пространство", fr="Espace disponible" WHERE key_code="SPACE_AVAILABLE";
UPDATE intl set en="Space between", ru="Расстояние между", fr="Espace entre" WHERE key_code="SPACE_BETWEEN";
UPDATE intl set en="Space usage", ru="использование пространства(ssn)", fr="Espace utilisé" WHERE key_code="SPACE_USAGE";
UPDATE intl set en="Split text into letters", ru="Разделить текст на буквы", fr="Eclater en lettres" WHERE key_code="SPLIINTO";
UPDATE intl set en="Split text into letters", ru="Разделить текст на буквы", fr="Eclater le texte en lettres" WHERE key_code="SPLITINTO";
UPDATE intl set en="Square", ru="Квадрат", fr="Carré" WHERE key_code="SQUARE";
UPDATE intl set en="The source and the destination are the same!", ru="Источник и место назначения совпадают.", fr="La source et la destination sont identiques!" WHERE key_code="SRC_SAME_DEST";
UPDATE intl set en="Start in the viewport", ru="Запустить в окне просмотра", fr="Lancement dans la fenêtre" WHERE key_code="STARTINVIEWPORT";
UPDATE intl set en="Delay before start", ru="Отложить старт", fr="Délai avant démarrage" WHERE key_code="STARTTIME";
UPDATE intl set en="Statistics", ru="Статистика", fr="Statistiques" WHERE key_code="STATISTICS";
UPDATE intl set en="Style", ru="Стиль", fr="Style" WHERE key_code="STYLE";
UPDATE intl set en="CSS3 attributes", ru="CSS3 атрибуты", fr="Attributs CSS3" WHERE key_code="STYLEOPT";
UPDATE intl set en="Subheading", ru="Подзаголовок", fr="Sous-titre" WHERE key_code="SUBHEADING";
UPDATE intl set en="Submenu", ru="Подменю", fr="Sous-menu" WHERE key_code="SUBMENU";
UPDATE intl set en="Submit", ru="Подтвердить", fr="Envoyer" WHERE key_code="SUBMIT";
UPDATE intl set en="Subscription", ru="Подписка", fr="Abonnement" WHERE key_code="SUBSCRIPTION";
UPDATE intl set en="Superposition", ru="Наложение", fr="Superposition" WHERE key_code="SUPERPOSITION";
UPDATE intl set en="SVG", ru="SVG", fr="SVG" WHERE key_code="SVG";
UPDATE intl set en="SVG code", ru="Код SVG", fr="Code SVG" WHERE key_code="SVG_CODE";
UPDATE intl set en="Table", ru="Таблица ", fr="Tableau" WHERE key_code="TABLE";
UPDATE intl set en="Tablet", ru="Планшетный компьютер", fr="Tablette" WHERE key_code="TABLET";
UPDATE intl set en="Tab & chart", ru="Таблицы и диаграммы", fr="Tableau & graphique" WHERE key_code="TAB_CHART";
UPDATE intl set en="Tag", ru="Тег", fr="Etiquetter" WHERE key_code="TAG";
UPDATE intl set en="Text", ru="Текст", fr="Texte" WHERE key_code="TEXT";
UPDATE intl set en="Text entry", ru="Ввод текста", fr="Champ de text" WHERE key_code="TEXT_ENTRY";
UPDATE intl set en="Thumbnail navigation", ru="Навигация по миниатюре", fr="Navigation via miniature" WHERE key_code="THUMBNAILNAVIGATION";
UPDATE intl set en="Timer", ru="Таймер", fr="Retardateur" WHERE key_code="TIMER";
UPDATE intl set en="Timeshift layer/slide", ru="Сдвиг по времени слоя/слайда", fr="Temporisation calque/planche" WHERE key_code="TIMESHIFT";
UPDATE intl set en="Title", ru="Заголовок ", fr="Titre" WHERE key_code="TITLE";
UPDATE intl set en="Thumbnail opacity", ru="Непрозрачность миниатюры", fr="Opacité de miniatures" WHERE key_code="TNACTIVEOPACITY";
UPDATE intl set en="Thumbnail container width", ru="Ширина содержимого миниатюры", fr="Largeur conteneur miniatures" WHERE key_code="TNCONTAINERWIDTH";
UPDATE intl set en="Thumbnail height", ru="Высота миниатюры", fr="Hauteur de miniatures" WHERE key_code="TNHEIGHT";
UPDATE intl set en="Inactive thumbnail opacity", ru="Включить непрозрачность миниатюры", fr="Opacité de miniatures inactives" WHERE key_code="TNINACTIVEOPACITY";
UPDATE intl set en="Thumbnail width", ru="Ширина миниатюры", fr="Largeur de miniatures" WHERE key_code="TNWIDTH";
UPDATE intl set en="Top", ru="Верх", fr="Haut" WHERE key_code="TOP";
UPDATE intl set en="Touch navigation", ru="Сенсорная навигация", fr="Navigation tactile" WHERE key_code="TOUCHNAV";
UPDATE intl set en="Transform origin", ru="Transform origin", fr="Origine de transformation" WHERE key_code="TRANSFORMORIGIN";
UPDATE intl set en="Transform origine in [X Y Z]", ru="Transform origine при входе [X Y Z]", fr="Origine de transformation d'entrée [X Y Z]" WHERE key_code="TRANSFORMORIGININ";
UPDATE intl set en="Transform origine out [X Y Z]", ru="Transform origine при выходе [X Y Z]", fr="Origine de transformation de sortie [X Y Z]" WHERE key_code="TRANSFORMORIGINOUT";
UPDATE intl set en="2D transition", ru="Переместить в 2D", fr="Transition 2D" WHERE key_code="TRANSITION2D";
UPDATE intl set en="3D transition", ru="Переместить в 3D", fr="Transition 3D" WHERE key_code="TRANSITION3D";
UPDATE intl set en="Transition timer", ru="Время перемещения", fr="Intervalle de transition" WHERE key_code="TRANSITION_TIMER";
UPDATE intl set en="Transition type", ru="Тип перемещения", fr="Type de transition" WHERE key_code="TRANSITION_TYPE";
UPDATE intl set en="Twitter Feed", ru="Новостная лента Twitter", fr="Twitter Feed" WHERE key_code="TWITTER_FEED";
UPDATE intl set en="Two ways slideshow", ru="Два режима слайдшоу", fr="Lire dans les deux sens" WHERE key_code="TWOWAYSLIDESHOW";
UPDATE intl set en="Type", ru="Тип", fr="Type" WHERE key_code="TYPE";
UPDATE intl set en="Underline", ru="Подчеркнуть", fr="Souligné" WHERE key_code="UNDERLINE";
UPDATE intl set en="Undo", ru="Отменить", fr="Défaire" WHERE key_code="UNDO";
UPDATE intl set en="Unexpected action", ru="Непредвиденное действие", fr="Action non attendue" WHERE key_code="UNEXPECTED_ACTION";
UPDATE intl set en="Ungroup", ru="Разгруппировать", fr="Dissocier" WHERE key_code="UNGROUP";
UPDATE intl set en="Unit", ru="Объединить", fr="Unité" WHERE key_code="UNIT";
UPDATE intl set en="Unknown error", ru="Неизвестная ошибка", fr="Erreur inconnue" WHERE key_code="UNKNOWN_ERROR";
UPDATE intl set en="Unknown mÃ©dia type (%s)", ru="Неизвестный тип файла (%s)", fr="Type de média inconnu (%s)" WHERE key_code="UNKNOWN_MEDIA_TYPE";
UPDATE intl set en="Unlock", ru="Разблокировать", fr="déverrouiller" WHERE key_code="UNLOCK";
UPDATE intl set en="Value doesn't match with the field {0}", ru="Значение не совпадает с полем {0}", fr="La valeur est différente du champ {0}" WHERE key_code="UNMACTH_VALUE";
UPDATE intl set en="Unreferenced message", ru="Сообщение без ссылки", fr="Message non référencé" WHERE key_code="UNREFERENCED_MSG";
UPDATE intl set en="Unset", ru="В начало", fr="Non précisé" WHERE key_code="UNSET";
UPDATE intl set en="Update", ru="Обновить", fr="Mettre à jour" WHERE key_code="UPDATE";
UPDATE intl set en="Updates", ru="Обновления", fr="Modifications" WHERE key_code="UPDATES";
UPDATE intl set en="Update the site", ru="Обновить сайт", fr="Modifier le site" WHERE key_code="UPDATE_SITE";
UPDATE intl set en="URL", ru="URL", fr="Url" WHERE key_code="URL";
UPDATE intl set en="HTML attributs", ru="Атрибуты HTML", fr="Attributs HTML" WHERE key_code="USERATTRIBUTES";
UPDATE intl set en="User classes", ru="Классы пользователей", fr="Classes utilisateurs" WHERE key_code="USERCLASS";
UPDATE intl set en="Username", ru="Имя пользователя", fr="Identifiant" WHERE key_code="USERNAME";
UPDATE intl set en="Users admin", ru="Администратор пользователей", fr="Admin utilisateurs" WHERE key_code="USERS_ADMIN";
UPDATE intl set en="Personnal spaces", ru="Личное пространство", fr="Espaces personnels" WHERE key_code="USERS_SPACES";
UPDATE intl set en="My parameters", ru="Параметры", fr="Mes paramètres" WHERE key_code="USER_PARAMS";
UPDATE intl set en="Privacy", ru="Конфиденциальность", fr="Confidentialités" WHERE key_code="USER_PRIVACY";
UPDATE intl set en="Remit", ru="Права администратора", fr="Attribution" WHERE key_code="USER_REMIT";
UPDATE intl set en="Security", ru="Безопасность", fr="Sécurité" WHERE key_code="USER_SECURITY";
UPDATE intl set en="My spaces", ru="Мои пространства", fr="Mes espaces" WHERE key_code="USER_SPACES";
UPDATE intl set en="Validate", ru="Подтвердить", fr="Valider" WHERE key_code="VALIDATE";
UPDATE intl set en="Video as background", ru="Использовать видео как фон", fr="Vidéo en fond" WHERE key_code="VDO_AS_BG";
UPDATE intl set en="Vertical", ru="Вертикальный", fr="Vertical" WHERE key_code="VERTICAL";
UPDATE intl set en="Site address", ru="Адрес сайта", fr="Adress du site" WHERE key_code="VHOST";
UPDATE intl set en="Video", ru="Видео", fr="Vidéo" WHERE key_code="VIDEO";
UPDATE intl set en="Videos", ru="Видео", fr="Vidéos" WHERE key_code="VIDEOS";
UPDATE intl set en="Comments thread", ru="Поток комментариев", fr="Fil de commentaires" WHERE key_code="VIDEO_COMMENT";
UPDATE intl set en="HTML5 native video", ru="Встроенное видео HTML5", fr="Vidéo native HTML5" WHERE key_code="VIDEO_NATIVE";
UPDATE intl set en="Video player", ru="Видеоплеер", fr="Lecteur vidéo" WHERE key_code="VIDEO_PLAYER";
UPDATE intl set en="Video thread", ru="Видеопоток", fr="Fil video" WHERE key_code="VIDEO_THREAD";
UPDATE intl set en="Viewbox", ru="Окно просмотра", fr="Fenêtre de vue" WHERE key_code="VIEWBOX";
UPDATE intl set en="The clipboard is void", ru="Буфер обмена пуст", fr="Le presse-papier est vide" WHERE key_code="VOID_CLIPBOARD";
UPDATE intl set en="You won't be able to revert this!", ru="Вы не сможете отменить это!", fr="Cette action sera irreversible!" WHERE key_code="WARN_NON_REVERTIBLE";
UPDATE intl set en="Watch", ru="Смотреть", fr="Regarder" WHERE key_code="WATCH";
UPDATE intl set en="Your permission is to weak to have access to this page", ru="У вас недостаточно прав для доступа к странице.", fr="Votre permission n'est pas suffisante pour accéder à cette page." WHERE key_code="WEAK_PRIVILEGE";
UPDATE intl set en="Widget", ru="Виджет", fr="Widget" WHERE key_code="WIDGET";
UPDATE intl set en="Widgets", ru="Виджеты", fr="Widgets" WHERE key_code="WIDGETS";
UPDATE intl set en="Widgets, modules", ru="Виджеты, модули", fr="Widgets, modules" WHERE key_code="WIDGETS_MODULES";
UPDATE intl set en="Auto-adjusted width", ru="Автоширина", fr="Largeur auto-ajustée" WHERE key_code="WIDTH_AUTO";
UPDATE intl set en="The window has been blocked by your navigator. Please, change the settings to allow the operation.", ru="Окно было заблокировано вашим браузером. Пожалуйста, измените настройки, чтобы разрешить действие. ", fr="La fenêtre n'a pu s'afficher parce que votre anvigateur l'en a empêchée. Veuillez changer les paramètres pour autoriser l'opération." WHERE key_code="WINDOW_BLOCKED";
UPDATE intl set en="The workshop contains no element", ru="Рабочее пространство не содержит элементов", fr="L'espace de travail ne contient aucun éléments" WHERE key_code="WORKSHOP_EMPTY";
UPDATE intl set en="Write", ru="Написать", fr="Ecrire" WHERE key_code="WRITE";
UPDATE intl set en="Wrong drag-and-drop area", ru="Неправильное перемещение", fr="La zone de glisser-déposer est incorrecte" WHERE key_code="WRONG_DROP_AREA";
UPDATE intl set en="X (abcsissa)", ru="Ось X абсцисс", fr="X (abscisse)" WHERE key_code="X";
UPDATE intl set en="Y (ordinate)", ru="Ось Y ординат", fr="Y (orodonnée)" WHERE key_code="Y";
UPDATE intl set en="Yes", ru="Да", fr="Oui" WHERE key_code="YES";
UPDATE intl set en="Your logo", ru="Логотип", fr="Votre logo" WHERE key_code="YOURLOGO";
UPDATE intl set en="Your logo style", ru="Стиль логотипа", fr="Style de votre logo" WHERE key_code="YOURLOGOSTYLE";
UPDATE intl set en="Your logo target", ru="Значение логотипа", fr="Cible de votre logo" WHERE key_code="YOURLOGOTARGET";
UPDATE intl set en="Youtube preview", ru="Предпросмотр YouTube", fr="Prévisualisation Youtube" WHERE key_code="YOUTUBEPREVIEW";
