ALTER TABLE mark DROP PRIMARY KEY;
ALTER TABLE mark ADD UNIQUE(`drum_id`);
ALTER TABLE mark ADD `sys_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE mark ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;