DELIMITER $

DROP PROCEDURE IF EXISTS `show_b2c_users`$
DROP PROCEDURE IF EXISTS `domain_list`$
DROP PROCEDURE IF EXISTS `authoritative_update`$
DROP PROCEDURE IF EXISTS `domain_revoke`$
DROP PROCEDURE IF EXISTS `domain_drumate_exists`$
DROP PROCEDURE IF EXISTS `role_unmap`$
DROP PROCEDURE IF EXISTS `domain_user_detail`$
DROP PROCEDURE IF EXISTS `role_reposition`$
DROP PROCEDURE IF EXISTS `analytic_drumates`$
DROP PROCEDURE IF EXISTS `analytic_hub_usage`$
DROP PROCEDURE IF EXISTS `analytic_hub_users`$
DROP PROCEDURE IF EXISTS `analytic_visit`$
DROP PROCEDURE IF EXISTS `analytics_connection`$
DROP PROCEDURE IF EXISTS `analytics_log`$
DROP PROCEDURE IF EXISTS `analytics_referer`$
DROP PROCEDURE IF EXISTS `cleanup_share_node`$
DROP PROCEDURE IF EXISTS `lookup_dmail`$
DROP PROCEDURE IF EXISTS `presignon`$
DROP PROCEDURE IF EXISTS `lookup_area`$
DROP PROCEDURE IF EXISTS `get_hub_header`$
DROP PROCEDURE IF EXISTS `get_hub_header_next`$
DROP PROCEDURE IF EXISTS `set_mailbox`$
DROP PROCEDURE IF EXISTS `get_innest_photo`$
DROP PROCEDURE IF EXISTS `dmail_exists`$
DROP PROCEDURE IF EXISTS `set_home_layout_2`$
DROP PROCEDURE IF EXISTS `online_status`$
DROP PROCEDURE IF EXISTS `set_home_layout`$
DROP PROCEDURE IF EXISTS `add_alias`$
DROP PROCEDURE IF EXISTS `set_finger_print`$
DROP PROCEDURE IF EXISTS `set_activation_key`$
DROP PROCEDURE IF EXISTS `top_news`$
DROP PROCEDURE IF EXISTS `gallery`$
DROP PROCEDURE IF EXISTS `news_flow`$
DROP PROCEDURE IF EXISTS `register_touch_request`$
DROP PROCEDURE IF EXISTS `store_request`$
DROP PROCEDURE IF EXISTS `log_signon`$
DROP FUNCTION IF EXISTS `set_env`$
DROP FUNCTION IF EXISTS `get_ident`$
DROP FUNCTION IF EXISTS `has_attachment`$
DROP FUNCTION IF EXISTS `hub_id_old`$
DROP FUNCTION IF EXISTS `backquoted_dbname`$
DROP FUNCTION IF EXISTS `drumate_photo_old`$
DROP FUNCTION IF EXISTS `SPLIT_STRING`$
DROP FUNCTION IF EXISTS `unique_username_next`$
DROP PROCEDURE IF EXISTS `yp_get_share_guest`$
DROP PROCEDURE IF EXISTS `yp_remove_guest`$
DROP PROCEDURE IF EXISTS `yp_delete_expired_guest`$
DROP PROCEDURE IF EXISTS `hub_list_by_owner`$
DROP PROCEDURE IF EXISTS `hub_list`$
DROP PROCEDURE IF EXISTS `hub_update_settings`$
DROP PROCEDURE IF EXISTS `hub_change_profile`$
DROP PROCEDURE IF EXISTS `hub_register`$
DROP PROCEDURE IF EXISTS `hub_search`$
DROP PROCEDURE IF EXISTS `hub_has_huber`$
DROP PROCEDURE IF EXISTS `hub_show_hubers`$
DROP PROCEDURE IF EXISTS `hub_remove_huber`$
DROP PROCEDURE IF EXISTS `hub_set_privilege`$
DROP PROCEDURE IF EXISTS `hub_add_huber`$
DROP PROCEDURE IF EXISTS `get_intl_msg`$
DROP PROCEDURE IF EXISTS `intl_get_by_group`$
DROP PROCEDURE IF EXISTS `intl_delete`$
DROP PROCEDURE IF EXISTS `intl_list_by_type`$
DROP PROCEDURE IF EXISTS `intl_get`$
DROP PROCEDURE IF EXISTS `intl_find`$
DROP PROCEDURE IF EXISTS `yp_get_expired_frozen_languages`$
DROP PROCEDURE IF EXISTS `yp_check_language_available`$
DROP PROCEDURE IF EXISTS `language_exists`$
DROP PROCEDURE IF EXISTS `yp_add_non_drumate`$
DROP PROCEDURE IF EXISTS `yp_remove_non_drumate`$
DROP PROCEDURE IF EXISTS `yp_delete_expired_non_drumate`$
DROP PROCEDURE IF EXISTS `plf_list_models`$
DROP PROCEDURE IF EXISTS `get_stylesheets`$
DROP PROCEDURE IF EXISTS `get_fonts`$
DROP PROCEDURE IF EXISTS `payment_initiate`$
DROP PROCEDURE IF EXISTS `payment_paid`$
DROP PROCEDURE IF EXISTS `payment_failed`$
DROP PROCEDURE IF EXISTS `payment_get`$
DROP PROCEDURE IF EXISTS `payment_get_by_status`$
DROP PROCEDURE IF EXISTS `subscription_get`$
DROP PROCEDURE IF EXISTS `subscription_update`$
DROP PROCEDURE IF EXISTS `get_ui_locale_next`$
DROP PROCEDURE IF EXISTS `get_ui_locale`$
DROP PROCEDURE IF EXISTS `get_backend_locale`$
DROP PROCEDURE IF EXISTS `token_btob_update1`$
DROP PROCEDURE IF EXISTS `token_generate_signup`$
DROP PROCEDURE IF EXISTS `common_hubs`$
DROP PROCEDURE IF EXISTS `get_profile_photo`$
DROP PROCEDURE IF EXISTS `hubs_watermark`$
DROP PROCEDURE IF EXISTS `get_dbname_by_entityid`$
DROP PROCEDURE IF EXISTS `test_sjon`$
DROP PROCEDURE IF EXISTS `default_page`$
DROP PROCEDURE IF EXISTS `get_unique_id`$
DROP PROCEDURE IF EXISTS `yp_find_country`$
DROP PROCEDURE IF EXISTS `yp_find_city`$
DROP PROCEDURE IF EXISTS `utils_search_countries`$
DROP PROCEDURE IF EXISTS `utils_get_countries`$
DROP PROCEDURE IF EXISTS `yp_get_countries`$
DROP PROCEDURE IF EXISTS `utils_search_cities`$
DROP PROCEDURE IF EXISTS `yp_get_cities`$
DROP PROCEDURE IF EXISTS `list_all_db`$
DROP PROCEDURE IF EXISTS `list_drumate_db`$
DROP PROCEDURE IF EXISTS `list_hub_db`$
DROP PROCEDURE IF EXISTS `log_activity`$
DROP PROCEDURE IF EXISTS `trace`$
DROP PROCEDURE IF EXISTS `create_anon_session`$
DROP PROCEDURE IF EXISTS `update_session`$
DROP PROCEDURE IF EXISTS `check_sid`$
DROP PROCEDURE IF EXISTS `cleanup_sessions`$
DROP PROCEDURE IF EXISTS `logout`$
DROP PROCEDURE IF EXISTS `hot_tech`$
DROP PROCEDURE IF EXISTS `get_error_map`$


DELIMITER ;